### ISSUE TITLE
segmentation using SOM from somoclu

### ISSUE THREAD

**Issue by fabien-w** [peterwittek/somoclu#100]
Hi Peter,
Thank you very much for this very nice package.
I am trying to use SOM to do a color simplification of an image. Let's say I have RGB image of 100 rows by 100 columns. On this image I run a SOM with rectangular gridType and 100 rows and 100 columns. The idea is to organize the colors of the image an to create the color palette of this image.
Is there a way to find the coordinates of the pixels original images in the map returned by SOM (in res$codes). 
I have tried to do this with the RGB color, that is find the rgb color of the pixel of the original image in the image returned by res$codes, but it seems that the RGB values returned by the SOM res$codes are slighty different than the original image RGB image. Am I right ? any suggestions ?
Thank your very much,
Fabien

**Comment by peterwittek** [comment]
It is extremely unlikely that you will find an exact match -- that is not what a SOM is for. What you want is the BMU for each pixel.

**Comment by fabien-w** [comment]
Thank you very much for your reply, Perfect.
