### ISSUE TITLE
Preprocessor Macro usage should be limited

### ISSUE THREAD

**Issue by sambitdash** [peterwittek/somoclu#103]
The code has a large number of pre-processor macros that may not be necessary and makes the code confusing.

Guarding pragma within #defines for omp may not be needed as unrecognized pragmas are ignored by compiler.

**Comment by peterwittek** [comment]
I saw your changes in PR #104. Let's hope that this forgotten compiler will not come back to haunt us. Thanks.

**Comment by sambitdash** [comment]
Actually, I am not too worried about the OpenMP ones, although I avoided their usage in the Julia implementation. The particular ones I was not very comfortable with were:

1. The _WIN32 on for loop iterators which has been now typedefed in `somoclu.h`. 
2. The CLI one which kind of changes function signature so can be made as an `archiver` object with default as NULL. 
3. HAVE_MPI which IMHO can be removed from each function code blocks into an aggregated place as a MPI handler object.

**Comment by peterwittek** [comment]
1. is now addressed with commits 7b41f5e75dcdc9be294730ce5ac3e528142dd620 and f46fe62e8cf83b5aaeca313807021c3313412f7c.

**Comment by peterwittek** [comment]
As for 2), I am trying to figure out why we needed CLI in the first place. We definitely need a different bail-out mechanism (l71-88 in `training.cpp`) depending on whether we run on the command line (MPI versus normal) or from a library. The call signature change might not be necessary, since there is boilerplate code for all interfaces anyway.

I am trying to remove the function signature change now. Do you have any recommendations for an elegant way of doing `my_abort`?

**Comment by sambitdash** [comment]
Since, you have library the library should throw an exception only. It's up to upstream code to decide what they do with it. If upstream code is say R or Python you have to handle the exception in the connector code and pass an error to those.

**Comment by peterwittek** [comment]
I exterminated the CLI macro from the function signatures. The rest is tougher. I understand the exception handling and I think it works fine, but when the CLI/MPI version calls `my_abort`, that should trigger a different mechanism.

The second part that is challenging to disentangle is the optional saving of intermediate data when called from CLI/MPI.

Basically, the CLI macro is left in two places in `training.cpp`, and I think it is a reasonable trade-off between readability and complexity. What do you think?

Regarding 3), I don't even know how to get started. If you can give me any pointers, that would be great.

**Comment by sambitdash** [comment]
I feel it may not be needed to include strstream just for one small case of appending an [int to string](https://github.com/peterwittek/somoclu/blob/7955d030c3043b87ab5c268e70919eeaba0d3752/src/training.cpp#L26). You could use `to_string` for the integer as well, removing another CLI guard. But this will be absolute nitpicking :-).  Having the CLI in the function argument created case of potential linker errors and one had to always keep in mind before calling are you needing it for CLI or non-CLI calls. 

I am not knowledgeable in MPI. But let me give some thoughts around it. Thanks a lot for the prompt changes.

**Comment by peterwittek** [comment]
Okay, this is done, the -DCLI flag is now removed. The only thing remaining is the MPI stuff, but I would rather leave that alone. CUDA testing will come later.

**Comment by sambitdash** [comment]
You could derive: `MPIRuntimeError` from `std::runtime_error`. In the constructor you could call all the stuff you are doing in `xxx_abort` routines. Then wherever you catch depending on the kind of exception take appropriate actions for closure.
