### ISSUE TITLE
How to get new BMU without retraining SOMn in Python?

### ISSUE THREAD

**Issue by Zub4ir** [peterwittek/somoclu#106]
Hi,

I think this a similar question to "Update SOM after training in R (question)".

But I'd like to calculate the BMUs on a new (updated) dataset without training the SOM again. The issue above mentioned that this is possible in the Python package without running the training function again (I don't want to update the codebook). I can't find it in the "Read the Docs" documentation.

I can use the resulting codebook on the new dataset and find my own BMUs using some numpy implementation, but I was wondering if it wouldn't be faster to use some (existing) implementation inside of SOMOCLU?

**Comment by peterwittek** [comment]
You need to use the methods [`get_surface_state`](https://somoclu.readthedocs.io/en/stable/reference.html#Somoclu.get_surface_state) to obtain the activation map of the new data and then get the corresponding BMUs with [`get_bmus`](https://somoclu.readthedocs.io/en/stable/reference.html#Somoclu.get_bmus).

**Comment by Zub4ir** [comment]
Thank you.
