### ISSUE TITLE
Is this package using Deep Learning?

### ISSUE THREAD

**Issue by jimmyjoseph1295** [peterwittek/somoclu#112]
I have tried looking for this in the docs etc but can't find it.
As far as I know, the columns/rows inputted are not specifying the network architecture?

Does this package have hidden layers? can I alter it?

Many Thanks

**Comment by peterwittek** [comment]
It's a [Kohonen map](https://en.wikipedia.org/wiki/Self-organizing_map): it is shallow by definition.
