### ISSUE TITLE
no value cells behavior 

### ISSUE THREAD

**Issue by khawar85** [peterwittek/somoclu#113]
Dear Experts.

Good mOrning. I hope you are fine. 
I want to ask two questions. 

1) First, when I put the cvs format file with 4 data columns, and ... some cells are without any value.. even without zero.. as there are some negative values, some zero, some positive, I removed the zeros with no value inside. the SOM training gives error.. as no value.. so, it it not possible to deal such data witout any values in some cells.

2) my second question is.. when I provide the full data file. then at one stage there is error like
Warning: passing the data in the constructor is deprecated.

.. is it dangerous for output?

3) Third .. that there are coordinates with x, y. How SOMOCLU will be plotted at the output. If you can guide me.. to map exactly on the grid. 
because data file has the 6 columns. first two with coordinates. last four with numbers of reading. Please help

Greetings

**Comment by peterwittek** [comment]
1. True. Data transformations are not within the scope of this project. The user is responsible for cleaning and transforming the data. There are n+1 tools for that in scikit-learn, pandas, and countless other frameworks.
2. No, it's fine. Although it is more elegant to pass the data in the `train` function.
3. I don't understand this. Your d dimensional data instances are in the rows of a matrix. SOM is a 2D embedding method that preserves the local topology of the d dimensional space. So obviously, you will only have x and y coordinates.
