### ISSUE TITLE
What VS version & Platform Toolset is somoclu-master compatible with?

### ISSUE THREAD

**Issue by pegasone** [peterwittek/somoclu#118]
I am asking this question as CUDA 9.1 (still) requires the VS2015 tool chain. While the CUDA samples do build successfully in VS2017 15.6.6 with Platform Toolset = Visual Studio 2015 (v140), the current somoclu-master does not. What specific configuration do I need to build this project? Thank you in advance.

**Comment by xgdgsc** [comment]
The last time I tried uses https://github.com/peterwittek/somoclu/blob/master/src/Windows/somoclu/somoclu.vcxproj , which seems to be v140. What error do you get?

**Comment by pegasone** [comment]
In somoclu.cpp, the first error is a syntax error related to the dots here:

```
    som map = {
      .nSomX = nSomX,
      .nSomY = nSomY,
      .nDimensions = nDimensions,
      .nVectors = nVectors,
      .mapType = mapType,
      .gridType = gridType,
      .get_distance = EuclideanDistance(nDimensions),
      .uMatrix = NULL,
      .codebook = new float[nSomY * nSomX * nDimensions],
      .bmus = NULL}
```

**Comment by xgdgsc** [comment]
This would hopefully fix the error and build successfully. If any further issue please comment.

**Comment by pegasone** [comment]
Thank you, but it crashes upon trying "somoclu data/rgbs.txt data/rgbs",
right here:



--Laurent

**Comment by pegasone** [comment]
[reformatted this posting] Thank you, but it crashes upon trying "somoclu data/rgbs.txt data/rgbs",
right here:

```
void get_bmu_coord(som map, float* data, unsigned int* coords, unsigned int n) {
    float mindist = 0.0f;
    float dist = 0.0f;

    /// Check map.nSomX * map.nSomY nodes one by one and compute the distance
    /// D(W_K, Fvec) and get the mindist and get the coords for the BMU.
    ///
    for (unsigned int som_y = 0; som_y < map.nSomY; som_y++) {
        for (unsigned int som_x = 0; som_x < map.nSomX; som_x++) {
            dist = map.get_distance(map.codebook + som_y * map.nSomX * map.nDimensions + som_x * map.nDimensions, <======
```

**Comment by xgdgsc** [comment]
Thanks! This hopefully would fix it.

**Comment by pegasone** [comment]
Excellent, thanks!
