### ISSUE TITLE
I have installed CUDA and changed the PATH in Linux, but still cannot use GPU mode while trainning. 

### ISSUE THREAD

**Issue by MQCodingFarmer** [peterwittek/somoclu#119]
After setting 'CUDAHOME ' variable, I installed somoclu following these steps:
`$ ./autogen.sh`
`$ ./configure --with-cuda=\software\cuda`
`$ make python`
`$ cd src/Python`
`$ python setup.py install`

But when I want to use GPU, It still doesn't work. the code and Error as follows:
 
`som = somoclu.Somoclu(n_columns, n_rows, data=data,maptype = "toroid",kerneltype =1)`

> RuntimeError                              Traceback (most recent call last)
> <timed eval> in \<module>()
> ~/anaconda3/lib/python3.6/site-packages/somoclu/train.py
> in train(self, data, epochs, radius0, radiusN, radiuscooling, scale0, scaleN, scalecooling)
> RuntimeError: Compiled without CUDA!

I've been working on this for a whole day.Can anyone help me Please! Thank you very much.

**Comment by peterwittek** [comment]
This is tricky. The parameters to `configure` do not make a difference. The Python setup script picks up the CUDA location from the `CUDAHOME` environment variable.

You have to ensure the following:

1. You compile the code with Anaconda's GCC.
2. CUDA is visible to the compilers.
3. NVCC is using Anaconda's GCC.

From what you describe, I gather that you accomplished 1-2. So check if NVCC wraps the correct compiler.

Delete the `build` folder in the Python subfolder, then run `pyhon setup.py build`. If the first line in the output is `Proceeding without CUDA`, then something is off with CUDA or NVCC.

**Comment by MQCodingFarmer** [comment]
I checked `which gcc` and find that I didn't compile the code with Anaconda's GCC. 

However, after changing it to `~/anaconda3/bin/gcc`,  It still doesn't work and it report the same ERROR.

Then I delete the `build` folder and run `setup.py`. There's no line with `Procedding without CUDA`. So I confused and I don't know how to ensure that **NVCC is using Anaconda's GCC**. 

Thank you very much!

**Comment by peterwittek** [comment]
That's intricate, see [this](https://stackoverflow.com/questions/44792279/set-default-host-compiler-for-nvcc). Yet, based on what you write, I do not think that this is the problem. The setup script cannot find your CUDA in the first place. Change these lines in `setup.py`

```python
try:
    CUDA = find_cuda()
except EnvironmentError:
    CUDA = None
    print("Proceeding without CUDA")
```

to

```python
CUDA = find_cuda()
```
The script will fail when you try to build, and you will get an error message why it cannot find CUDA.

**Comment by MQCodingFarmer** [comment]
It says  `  File "setup.py", line 134, in <module>
    if CUDA is not None:
NameError: name 'CUDA' is not defined
`  
So, there dose exist an `EnvironmentError`. What should I do next? Still the problem of GCC?

Thank you~

**Comment by peterwittek** [comment]
Are you sure you left in the line `CUDA = find_cuda()`?
