### ISSUE TITLE
Plot labels on view_component_planes

### ISSUE THREAD

**Issue by DoctorRad** [peterwittek/somoclu#122]
It would be very useful to be able to label each plot produced by `view_component_planes`. I use the Python interface, so passing in a list of component names would be my preferred interface.

**Comment by peterwittek** [comment]
The `view_whatever` methods return a figure object that you can manipulate as you please. I see that the problem with view_component_planes is that it returns the figure object of the last component, but not the full list of them. The cheap workaround is to pass the `dimension` argument, and iterate over all dimensions. So you get a figure object for each, and you can add your labels.

**Comment by DoctorRad** [comment]
Many thanks, I wasn't aware that that was how `dimension` worked. Is it a simple zero-based index?

**Comment by peterwittek** [comment]
It is.
