### ISSUE TITLE
How to limit core count use?

### ISSUE THREAD

**Issue by Zub4ir** [peterwittek/somoclu#126]
Hi,

How do I limit the available cores to the train function (and SOMOCLU in general)? The training function uses all my 4 cores pushing my CPU to 100%. I'd like to keep some free CPU so that I can still work on my PC.

**Comment by xgdgsc** [comment]
You can try the `OMP_NUM_THREADS` environment variable.

**Comment by Zub4ir** [comment]
I just used the operating system resource limiting functionality.
