### ISSUE TITLE
Error in R: CUDA kernel not compiled 

### ISSUE THREAD

**Issue by Tenceto** [peterwittek/somoclu#132]
I'm trying to train a SOM using the GPU in R, but when setting `kernelType <- 1` and executing the code, the following error appears:
`Error: CUDA kernel not compiled `

Does anyone know how to solve this? I'm on Ubuntu 18.04 and my GPU is a GeForce GTX 1080 Ti.

**Comment by xgdgsc** [comment]
Did you compile yourself following the instruction at https://github.com/peterwittek/somoclu#interfaces or installed from CRAN?

**Comment by Tenceto** [comment]
I tried with both, and neither worked. First I tried running `install.packages('Rsomoclu')` directly from RStudio. Then I uninstalled the package and performed the following command in the shell:
`
R CMD INSTALL Rsomoclu_1.7.5.tar.gz --configure-args=/usr/local/cuda`

The problem with this is that the following warnings appear during compilation:

```
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /usr/local/cuda
```

So I believe the error is due to those warnings, but I dont' know why they appear, as CUDA is installed in that directory. Do you know what can be done to fix this?

**Comment by xgdgsc** [comment]
https://github.com/tsiv/ccminer-cryptonight/issues/10 ?

**Comment by Tenceto** [comment]
Sorry for my ignorance, I'm rather new to all this. That seems to be the same error I'm getting, but I don't see where the `--with-cuda` argument is passed in the line I executed on the shell. As I wrote above, I did this:

`R CMD INSTALL Rsomoclu_1.7.5.tar.gz --configure-args=/usr/local/cuda`

Is there anything wrong with it? How can I relate this to the link you mentioned?

**Comment by xgdgsc** [comment]
Sorry, the doc is outdated after a previous update. https://github.com/peterwittek/somoclu/blob/master/src/R/configure-gpu is the expected configure file to use when building against CUDA. But previous commands doesn' t work any more, I haven' t figured out how to build this, will try later.

**Comment by Tenceto** [comment]
I'm not sure I'm following you, but judging from what I understood, currently there is no way to build the library? If this is the case, please let me know if you were able to figure it out.

Thanks for the help! Really appreciate it.

**Comment by xgdgsc** [comment]
If old version would work, you can use https://cran.r-project.org/src/contrib/Archive/Rsomoclu/Rsomoclu_1.6.2.1.tar.gz which seems to work with the command `R CMD INSTALL Rsomoclu_1.6.2.1.tar.gz --configure-args=/usr/local/cuda`

**Comment by xgdgsc** [comment]
https://cran.r-project.org/src/contrib/Archive/Rsomoclu/Rsomoclu_1.7.2.tar.gz is the latest version that would work with this command.

**Comment by Tenceto** [comment]
Cool, that worked as a charm. Thank you so much for your help!
