### ISSUE TITLE
The MATLAB CUDA interface crashes with unknown reasons

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/somoclu#14]
At least this is the case with 2013a.

**Comment by xgdgsc** [comment]
This seems to be fixed with https://github.com/peterwittek/somoclu/commit/6bd4bb96acda7fc827a4d3e642aa07bea4b55144 ，you can test to make sure.

**Comment by peterwittek** [comment]
I have no means to verify this, but I think we can close this. Thanks.
