### ISSUE TITLE
How to use view_activation_map?

### ISSUE THREAD

**Issue by JimmyGao0204** [peterwittek/somoclu#143]
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import somoclu

c1 = np.random.rand(50, 3)/5
c2 = (0.6, 0.1, 0.05) + np.random.rand(50, 3)/5
c3 = (0.4, 0.1, 0.7) + np.random.rand(50, 3)/5
c4 = (0.5, 0.1, 0.6) + np.random.rand(50, 3)/5
c5 = (0.4, 0.1, 0.6) + np.random.rand(50, 3)/5

data = np.float32(np.concatenate((c1, c2, c3)))
colors = ["red"] * 50
colors.extend(["green"] * 50)
colors.extend(["blue"] * 50)
labels = range(150)

n_rows, n_columns = 100, 160
som = somoclu.Somoclu(n_columns, n_rows, compactsupport=False)
som.train(data)

surface_state = som.get_surface_state()

som.view_activation_map(surface_state, 0, labels = labels)

 I have tried to plot a activation map using the above code, but it doesn't work. Does anybody know how to fix this problem?Thank you very much.

**Comment by xgdgsc** [comment]
You cannot specify both, 

```
som.view_activation_map(None, 0, labels = labels)
```
would work

**Comment by lidiasm** [comment]
Hi!!

I don't understand the meaning of specifying an index of the data to view the activation map of the model. I want to see how the data are spread in the model, like the image below. Anyone can explain how can I achieve this with somoclu library?
![Test 1 - BMU autumn](https://user-images.githubusercontent.com/14909267/87650518-12825b00-c752-11ea-8a81-d756cac16027.png)

**Comment by xgdgsc** [comment]
You could checkout [ipython-notebooks/Somoclu in Python.ipynb at ff373eecb8f62484880b4b0e7064eb60ccc50ddf · peterwittek/ipython-notebooks](https://github.com/peterwittek/ipython-notebooks/blob/ff373eecb8f62484880b4b0e7064eb60ccc50ddf/Somoclu%20in%20Python.ipynb) on the label section.
