### ISSUE TITLE
How can I list the clustering results from somoclu?

### ISSUE THREAD

**Issue by mezaacor** [peterwittek/somoclu#147]
I would like to list the clustering results for every row. How can I do that?

Thanks a lot, 

RM

**Comment by goleng** [comment]
Hi @mezaacor , I came across this python wrapper. It might be of help to you. [som-learn](https://pypi.org/project/som-learn/)

**Comment by mezaacor** [comment]
Thanks a lot @goleng 
I am going to check som-learn
