### ISSUE TITLE
Missing somoclu/somoclu_wrap.cxx in source folder for 1.7.5

### ISSUE THREAD

**Issue by eidalex** [peterwittek/somoclu#148]
Hi there, 
First of all thanks for the package I am eagger to use it with Python ! 
Well then, I have successfully built the project for Windows 10 (Visual Studio 2017 and CUDA 10.1) however when I want to build the Python package from it the script cannot find _somoclu_wrap.cxx_ inside its folder. I have the error :
`c1xx: fatal error C1083: Impossible d'ouvrir le fichier source : 'somoclu\somoclu_wrap.cxx' : No such file or directory`
Indeed, I searched inside the whole project but it is not there... Am I missing anything in the process ? Would you please help me ?
Thanks in advance, 
Kind regards

**Comment by xgdgsc** [comment]
Downloading from pypi includes that file.

**Comment by eidalex** [comment]
Indeed, thanks. I am compiling with it and I 'll keep you posted on the result.
