### ISSUE TITLE
Licensing and GPL

### ISSUE THREAD

**Issue by achapkowski** [peterwittek/somoclu#151]
I really like somoclu, but the GPL license forces anyone who uses the license to be GPL, can the license be switched to something like Apache 2.0?

**Comment by xgdgsc** [comment]
I' d like to. But the main problem is the main project owner dead in avalanche last year. And I have no way to get his consent on this. Do you know any previous example of license change after owner dies?

**Comment by achapkowski** [comment]
well that is a good question, I would guess that you could change it if it is agreed upon by the maintainers.

**Comment by achapkowski** [comment]
https://www.wired.com/story/giving-open-source-projects-life-after-a-developers-death/

**Comment by xgdgsc** [comment]
I found peter changed license for somoclu.jl https://github.com/peterwittek/Somoclu.jl/issues/6 . Maybe it' s fine to change this as it isn' t much against his will?

**Comment by achapkowski** [comment]
Does anyone have the ability to merge PRs from this repo?

**Comment by achapkowski** [comment]
PR https://github.com/peterwittek/somoclu/pull/152 resolves this issue.
