### ISSUE TITLE
MATLAB interfece Batch algorithm

### ISSUE THREAD

**Issue by bedassa** [peterwittek/somoclu#153]
I understood that somoclu  is parallel and batch training algorithm. I run the test somoclu_train in the MATLAB interfece and sTrain shows a seq algorithm.  I need batch algorithm as I am dealing with large dataset. Please, I need a tip how to change it  into  batch  algorithm

**Comment by xgdgsc** [comment]
What do you mean by not batch? The cpp implementation is batch.

**Comment by bedassa** [comment]
I run mex_interface_test.m which is the test file in the somoclu/src/Matlab . The sTrain indicates seq algorithm. I need how to change to batch. Thank you
type: 'som_train'
          algorithm: 'seq'
          data_name: 'D'
              neigh: 'gaussian'
               mask: [3×1 double]
         radius_ini: 50
         radius_fin: 1
          alpha_ini: NaN
         alpha_type: 'linear'
           trainlen: 100
               time: '24-Jul-2020 16:06:18'
     radius_cooling: 'linear'
        kernel_type: 0
    compact_support: 0
       neighborhood: 'gaussian'
             scale0: 0.1000
             scaleN: 0.0100
           stdCoeff: 0.5000
            verbose: 0
           gaussian: 1

**Comment by xgdgsc** [comment]
That' s only a string filling to reuse som toolbox data structure. You can change https://github.com/peterwittek/somoclu/blob/master/src/MATLAB/somoclu_train.m#L72 if you want. The call to somoclu cpp code is calling a batch algorithm.

**Comment by bedassa** [comment]
That is awesome. Thanks!!
