### ISSUE TITLE
R interface visual capabilities

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/somoclu#16]
The current R interface does not do anything but returns the structure it got from C++. Some simple visualization routines like the ones for the Python interface would make a big difference.

**Comment by xgdgsc** [comment]
I added the function to convert to kohonen for plotting in https://github.com/peterwittek/somoclu/commit/c04fe078233926b28ae0fb945662094aea199772 . Do you think it is a good way?

**Comment by peterwittek** [comment]
Wow, I just tried it, it is impressive. Thanks very much, we can close this.
