### ISSUE TITLE
Can I set the random seed?

### ISSUE THREAD

**Issue by yanzastro** [peterwittek/somoclu#163]
Can we set the random seeds to initialize the SOM?

**Comment by xgdgsc** [comment]
https://github.com/peterwittek/somoclu/blob/4e467051cf1b291c498c5e3972e597ce4f57bfab/src/training.cpp#L272   in Cpp, in R like https://github.com/peterwittek/somoclu/issues/51

**Comment by yanzastro** [comment]
thanks! is it possible to set it from python?

**Comment by xgdgsc** [comment]
generate the initialcodebook by your seed and pass to the constructor?

**Comment by yanzastro** [comment]
sounds like a great idea! So I just run something like:

```
codebook_ini = init(data, seed)  # init() is a pre-defined function to initialize the codebook
som.codebook = codebook_ini
som.train(...)
```
is it correct?
