### ISSUE TITLE
conda-forge PackagesNotFoundError

### ISSUE THREAD

**Issue by torluca** [peterwittek/somoclu#166]
Hi all,

I'm on an M1 Mac and I'm trying to install somoclu via conda, since the version in pip does not allow me to train the SOM.

The error I get is

`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - somoclu

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

Any idea why the package is not present on conda despite trying all the possible formulas here and in somoclu-feedstock?

Thanks for the help!

Luca

**Comment by xgdgsc** [comment]
We've never tried to build this on M1 and I don' t have access to a M1 device for now. Does the https://anaconda.org/conda-forge/somoclu/1.7.5/download/osx-64/somoclu-1.7.5-py310h700695d_1005.tar.bz2 x64 version work?

**Comment by torluca** [comment]
Thanks a lot for the fast reply. 

I installed it with

conda install somoclu-1.7.5-py310h700695d_1005.tar.bz2

but when importing it gives the same warning as in pip:

Warning: the binary library cannot be imported. You cannot train maps, but you can load and analyze ones that you have already saved.
If you installed Somoclu with pip on macOS, this typically means missing a linked library. If you compiled Somoclu with GCC, please make sure you have set DYLD_LIBRARY_PATH to include the GCC path. For more information, please refer to the documentation.

**Comment by xgdgsc** [comment]
Did you install the M1 version of Anaconda? Have you tried installing the x64 version of anaocnda https://repo.anaconda.com/archive/Anaconda3-2022.10-MacOSX-x86_64.pkg ?

**Comment by torluca** [comment]
I have the M1 version, as far as I know you can install the arm64 version only for compatibility

**Comment by xgdgsc** [comment]
https://www.anaconda.com/blog/apple-silicon-transition


x64 should also run
