### ISSUE TITLE
R CUDA support in new build structure

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/somoclu#17]
With commit 73abe64e4dcb0d9de363a9a01b9a0dbe546e0194, the scripts that were floating around for the R interface were merged to a Makefile target. To build the source distribution for R, just issue `make r`.

The R directory contains a configure script by default. If we build the module without CUDA, the script just exits and the usual R compilation procedure starts. To build with CUDA, you have to supply a parameter to the R install system:

`R CMD INSTALL Rsomoclu_1.5.tar.gz --configure-args=/path/to/cuda`

The `.so` file is built correctly and the module is installed, but the test fails. Please look into this.

**Comment by xgdgsc** [comment]
`R CMD INSTALL Rsomoclu_1.5.tar.gz --configure-args=/path/to/cuda`
doesn' t build for me. After some changes as https://github.com/peterwittek/somoclu/commit/250ced354c886b7989ea906fd92b1ddf7b0bf313 shows, I still get: 
```
g++ -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro -o Rsomoclu.so Rsomoclu.o denseCpuKernels.o sparseCpuKernels.o mapDistanceFunctions.o training.o uMatrix.o -I/home/gsc/R/x86_64-unknown-linux-gnu-library/Rcpp/include -DHAVE_R -DCUDA denseGpuKernels.cu.co -lgomp -L/opt/cuda/lib64 -lcudart -lcublas -L/usr/lib64/R/lib -lR
** libs
** arch - 
make -C src all
make[1]: *** src: No such file or directory.  Stop.
Makefile:19: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: compilation failed for package ‘Rsomoclu’
```

**Comment by peterwittek** [comment]
My bad, 56be992b1a1e45d95a786b3afb5e760465d71f70 fixes it.

**Comment by xgdgsc** [comment]
With https://github.com/peterwittek/somoclu/commit/833b0d69cb1e0e25775aa550e1b78b47d35e00ea#diff-bf1484e3b9ef79c263379afd79763253R19, it builds and runs fine in both kernels for me.

**Comment by peterwittek** [comment]
I just checked, it works perfectly. Thank you.
