### ISSUE TITLE
Warning: the binary library cannot be imported. You cannot train maps, but you can load and analyze ones that you have already saved. If you installed Somoclu with pip on Windows, this typically means missing DLLs. Please refer to the documentation.

### ISSUE THREAD

**Issue by Artem-geo** [peterwittek/somoclu#170]
Hello! 
I'm trying to install the somoclu library within the conda environment using pip. While importing the library the following warning arises "Warning: the binary library cannot be imported. You cannot train maps, but you can load and analyze ones that you have already saved. If you installed Somoclu with pip on Windows, this typically means missing DLLs. Please refer to the documentation."
I've tried all installation variants described in the #28 issue. Both MSVCP90.DLL and VCOMP90.DLL files were downloaded and placed into the .\System32 and .\SysWOW64 folders. I keep getting the warning and can't train a map. 
How can the issue be solved?

**Comment by xgdgsc** [comment]
Try WSL?

**Comment by Artem-geo** [comment]
> Try WSL?
No. Could you explain how this can be done?

**Comment by xgdgsc** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install  and use the conda forge linux version. Performance should be similar.

**Comment by Artem-geo** [comment]
Thanks. Now it works.
