### ISSUE TITLE
MATLAB compile scripts as Makefile targets

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/somoclu#18]
The Python and R scripts were merged into the Makefile as targets to simplify the procedure. Please do the same thing with the MATLAB scripts when you finish your work on [feature/matlab](https://github.com/peterwittek/somoclu/tree/feature/matlab). The Windows .bat can stay, naturally.

**Comment by xgdgsc** [comment]
OK.

**Comment by peterwittek** [comment]
Commit 8d996deb1cd49e527b74c21ab51a2f1f72cc8496 does this.
