### ISSUE TITLE
MATLAB interface integration with som toolbox

### ISSUE THREAD

**Issue by xgdgsc** [peterwittek/somoclu#19]
Codebook integration is fine, but som_umat() in som toolbox return different size umatrix compared with somoclu/Databionic ESOM Tools, there seem to be conceptual differences that need to be sorted out and enhance the integration accordingly.

**Comment by peterwittek** [comment]
Noted. Thanks for looking into this.

**Comment by peterwittek** [comment]
Any chance to make progress with this?

**Comment by xgdgsc** [comment]
Added some instructions for visualization in both SOM toolbox and Databionic ESOM Tools in https://github.com/peterwittek/somoclu/commit/431512db057868c6188cf0c1ba0491f067868e8b. I think the current instructions should be enough for both users.

**Comment by peterwittek** [comment]
This is perfect, thanks.
