### ISSUE TITLE
Rsomoclu with negative values

### ISSUE THREAD

**Issue by waynefoltaERI** [peterwittek/somoclu#22]
I scaled (subtract mean, divide by SD) my data before submitting to Rsomoclu -- consistent with using R's other som functions. This results(in Rsomoclu) in no codebook values below 0, which means nothing below the mean of the unscaled variables.

The documentation mentions "With random initialization, the initial codebook will be filled with random numbers ranging from 0 to 1. Either supply your own initial codebook or normalize your data to fall in this range." but it does not talk about how the initial codebook influences the final codebook values. Are negative values even possible? Can codebook values cross from positive to negative values? Is this an issue with R's native double-precision floats not mapping into Somoclu's single-precision floats?

Please either modify the algorithm or expand on the documentation to make clear the effects of the initial codebook values, etc.

**Comment by peterwittek** [comment]
I just tried it from Python, and yes, codebook values can take negative values. Naturally, the initial codebook has a huge impact on the final map, but this is expected for any SOM implementation, so I do not find it necessary to elaborate it further in the documentation.

It is, however, not advised to have negative values in the features, especially if the codebook is initialized from 0 to 1. This comes from the batch training nature of the parallel implementation. The batch update rule will change the codebook values with weighted averages of the data points, and with negative values, the updates can cancel out. This is a good point, I have not thought about this before, and it is definitely worth documenting. Thanks for pointing this out, I will update the documentation when I can.

**Comment by peterwittek** [comment]
Commit dcb1b2230a233c5d94b2e0f711da1f113aa557d8 extends the documentation by a paragraph on this.
