### ISSUE TITLE
Neighborhood Function Selection

### ISSUE THREAD

**Issue by brogie62** [peterwittek/somoclu#23]
Could you allow for user selection of neighborhood function beyond Gaussian? I would like the option of bubble but there are other functions that different users may prefer. 

Thanks for the great work!

**Comment by peterwittek** [comment]
Could you give us a reference to this neighbourhood function? I am not familiar with it. Thanks.

**Comment by brogie62** [comment]
![image](https://cloud.githubusercontent.com/assets/8990710/11324072/df5acd8c-90f3-11e5-824b-63100a2b4f32.png)
It is a simple cut-off or square function where all nodes within the radius are affected equally. It is the only neighborhood function in the Matlab Neural Network Toolbox and in the R package 'kohonen'. It is one of 2 choices (along with Gaussian) in the R package 'som'.

**Comment by peterwittek** [comment]
Commit 1e6988b65b77b651fc4b8c0dbbd876edb2a5704c implements choosing between bubble and Gaussian neighborhood functions across all interfaces (CLI, API, Python, R, MATLAB). Please test it. Once it works, I close this issue.

For future reference, the above extract is from [this paper](http://dx.doi.org/10.1007/978-3-642-21566-7_14). The paper concludes that "[t]"he bubble neighboring function yields the worst result for all the data sets analyzed." Nevertheless, we have it now.

Please note that Somoclu does not have a compact support for the neighborhood function by default. This means that in Eq. (2), N_c contains all nodes. To recover the behavior in Eq. (2), request a compact support with the corresponding optional parameter.

Also note that the Gaussian neighborhood in Somoclu is slightly different from Eq. (3): the eta rank does not appear in the denumerator.

**Comment by brogie62** [comment]
Thanks Peter. I am aware of the conclusions from that paper. Parameter optimization studies conducted on my data sets gives the reverse.

**Comment by peterwittek** [comment]
This surely isn't the best paper ever written on self-organizing maps, so I am not surprised at your findings. Please give it a go with the new bubble neighborhood function and let me know if it works as expected.

**Comment by brogie62** [comment]
I am trying to install your updated R package but am getting an error:
'Error in getOctD(x, offset, len) : invalid octal digit'
I have never installed from source before so I am guessing I am doing something wrong.
I have previously been running from the CLI but thought R would be a faster test than re-compiling.

**Comment by peterwittek** [comment]
I tested the R version and I did not have any problems (GCC 5.2.2 and R 3.2.2, freshly installed Rcpp). @xgdgsc, do you have an insight on this?

**Comment by xgdgsc** [comment]
Might be [file corruption](http://stackoverflow.com/questions/18652923/error-in-getoctdx-offset-len-invalid-octal-digit) ? How did you install the packege? What operating system/ which version of R do you use?

**Comment by brogie62** [comment]
Ubuntu 14.04
R 3.0.2
gcc 4.8.2

This is on an AWS instance. It may be that I am installing the wrong file or poor command syntax. I used R CMD INSTALL trying both the Rsomoclu.R and the Rsomoclu.cpp files and got the same error for both.

**Comment by peterwittek** [comment]
I just noticed there was an unrelated typo in the R version. Please use the latest git, I fixed the problem.

This is what I do:

    git clone https://github.com/peterwittek/somoclu
    cd somoclu
    ./autogen.sh
    ./configure
    make r
    R

Then from the R command line, I install Rcpp from CRAN and RScomoclu from source:

    install.packages("Rcpp")
    install.packages("./src/Rsomoclu_1.5.tar.gz", repos=NULL, type="source")

This works for me. Sorry for the trouble, I hope you get it working. Once we go through with this basic testing, we can do a minor release to make it available on CRAN.

**Comment by brogie62** [comment]
Compiled and tested Rsomoclu. Found that I got very different results using gaussian than I did from the CLI version of Somoclu. Decided to test prior version (1.5) of Rsomoclu. With the same parameters the outcome is very different between the two interfaces, R and CLI. The CLI results are more in line with experience using other som packages. Rsomoclu also outputs the BMUs as a list that is 2 x input rows, not 'x' and 'y' columns like CLI. Not sure if Rsomoclu is xxxxx... then yyyyy... or xyxyxyxy... The column is headed 'x'.

**Comment by peterwittek** [comment]
The main difference between the R version and all the other version is that the R wrapper uses R's random number generator for initializing the map. This might result in vastly different maps.

You are right, the encoding for BMUs is xyxy...

This is becoming unrelated to the original issue, so please open a new one if you see problems with the R wrapper. We do not really have R expertise, so it is quite limited what we can do, but opening an issue can never hurt.

**Comment by peterwittek** [comment]
Did you have a chance to test the bubble distance?

**Comment by peterwittek** [comment]
Actually, the bubble distance only makes any sense with a compact support. I changed the code accordingly (commit 3a2579323fc60a76b5fb9801932e5c7fb97d4bb8), and with that, I believe this issue is resolved.
