### ISSUE TITLE
Query in compilation with cuda and matlab

### ISSUE THREAD

**Issue by abhshah** [peterwittek/somoclu#24]
Hello,

I am trying to compile the program with CUDA and MATLAB. After I do the ./configure and make all. I go inside the source folder to make MATLAB.  And am getting the following error-

make: *** No rule to make target `denseGpuKernels.cu.o', needed by `matlab'.  Stop.

Do I need to change the Makefile.
I will appreciate any help I can get. Thank you.
 Following is the Makefile that was generated-

# src/Makefile.  Generated from Makefile.in by configure.

# Package-related substitution variables
package = Somoclu
version = 1.5
tarname = somoclu
distdir = $(tarname)-$(version)

# Prefix-related substitution variables
prefix   = /Users/abhshah/Project_data/new_project/somoclu
exec_prefix    = ${prefix}
bindir   = ${exec_prefix}/bin
libdir   = ${exec_prefix}/lib

# Tool-related substitution variables
CXX              = g++
CXXFLAGS       = -fPIC -fopenmp -Ofast -march=native
LIBS             =
DEFS           = -DHAVE_CONFIG_H
INSTALL        = /usr/bin/install -c
INSTALL_DATA   = ${INSTALL} -m 644
INSTALL_PROGRAM= ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
CUDA_CFLAGS    = -I/usr/local/cuda-6.5//include -use_fast_math -Xcompiler "-fPIC -fopenmp -Ofast -march=native"
CUDA_LIBS      = -lcudart -lcublas
CUDA_LDFLAGS   = -L/usr/local/cuda-6.5//lib64
NVCC           = /usr/local/cuda-6.5//bin/nvcc
MPI_INC        =
MPI_LIBDIR     =
MPI_LIBS       =
MATLAB_ROOT    = /opt/matlab/R2015a/
MEX_BIN        = /opt/matlab/R2015a//bin/mex

# VPATH-related substitution variables
srcdir   = .

LIBOBJS=sparseCpuKernels.o denseCpuKernels.o mapDistanceFunctions.o training.o uMatrix.o

MEX_FLAGS=-I./
MEX_LIBS=-lgomp
MEX_OBJS=sparseCpuKernels.o denseCpuKernels.o mapDistanceFunctions.o training.o uMatrix.o

ifdef CUDA_LIBS
    LIBOBJS+=denseGpuKernels.cu.co
    MEX_FLAGS+=-I"$(MATLAB_ROOT)/toolbox/distcomp/gpu/extern/include/" -DCUDA
    MEX_LIBS+=$(CUDA_LDFLAGS) $(CUDA_LIBS) -lnvblas -lmwgpu
    MEX_OBJS+=denseGpuKernels.cu.o
endif

OBJS=$(LIBOBJS) io.o somoclu.o

all: somoclu

lib: $(LIBOBJS)
    $(CXX) -g $(DEFS) $(CXXFLAGS) $(CUDA_LDFLAGS) ${MPI_LIBDIR} -shared -o libsomoclu.so $^ $(LIBS) $(CUDA_LIBS) ${MPI_LIBS}

somoclu: CXXFLAGS+= -DCLI
somoclu: $(OBJS)
    $(CXX) $(DEFS) $(CXXFLAGS) $(CUDA_LDFLAGS) ${MPI_LIBDIR} -o $@ $^ $(LIBS) $(CUDA_LIBS) ${MPI_LIBS}

%.o: %.cpp
        $(CXX) $(DEFS) $(CXXFLAGS) ${MPI_INC} -I$(srcdir) -I.. -o $@ -c $(srcdir)/$<

%.cu.co: %.cu
        $(NVCC) $(DEFS) $(CUDA_CFLAGS) ${MPI_INC} -I$(srcdir) -I.. -o $@ -c $(srcdir)/$<

matlab: $(MEX_OBJS)
#   if [ -e denseGpuKernels.cu.co ]; then cp denseGpuKernels.cu.co denseGpuKernels.cu.o; fi
    $(MEX_BIN) $(MEX_FLAGS) MATLAB/MexSomoclu.cpp $(MEX_OBJS) $(MEX_LIBS)

matlab_clean: clean
    -rm -f MexSomoclu* denseGpuKernels.cu.o

python:
    mkdir -p ./Python/somoclu/src

**Comment by peterwittek** [comment]
My bad, I introduced a bug yesterday to the MATLAB CUDA version. Please try the latest git, it should be working now.

**Comment by peterwittek** [comment]
According to the response to the duplicate issue #25, this has been resolved.
