### ISSUE TITLE
wrap_train

### ISSUE THREAD

**Issue by dinos66** [peterwittek/somoclu#28]
Hello.

While using somoclu (windows7, python3.4) and calling the som.train() command (with and without args), I get the following error: 
som.train(epochs=epochs, radius0=radius0, scale0=scale0)
  File "C:\Python34\lib\site-packages\somoclu\train.py", line 158, in train
    wrap_train(np.ravel(self._data), epochs, self._n_columns, self._n_rows,
NameError: name 'wrap_train' is not defined
Any ideas?

Thank you!

**Comment by xgdgsc** [comment]
There seems a problem with my pre-built wheel package. I will rebuild them.

**Comment by xgdgsc** [comment]
I rebuilt them and uploaded to https://github.com/peterwittek/somoclu/releases/tag/1.6 because pypi doesn' t allow files with the same name get reuploaded after deletion. And I remember it may not a building problem as https://github.com/peterwittek/somoclu/tree/master/src/Python#installation documented, you can try using  Dependency Walker on  `site-packages\_somoclu_wrap.pyd`. Usually right version (32/64bit) of vcomp90.dll, msvcp90.dll, msvcr90.dll should be put to C:\Windows\System32 or C:\Windows\SysWOW64, before you try the new built packages.

**Comment by dinos66** [comment]
It must have been the build, cause I reinstalled it using the new 1.6 which you uploaded and it seems to be working fine.

**Comment by xgdgsc** [comment]
OK. Thanks for pointing this out. Closing this.

**Comment by wooandoo** [comment]
Hi,

I still have the error with os x 10.10 and somoclu 1.6.1.
Do you have an idea?

**Comment by dinos66** [comment]
Apologies for checking but did you delete all somoclu files and reinstalled fresh?

**Comment by xgdgsc** [comment]
@wooandoo How did you install? Wheel package or running setup.py?

**Comment by wooandoo** [comment]
@xgdgsc I use python 3.5 in pineapple (iPython on OSX)
@dinos66 it was my first installation

**Comment by xgdgsc** [comment]
@wooandoo I just compiled a wheel package for 3.5 you can try installing it https://pypi.python.org/packages/3.5/s/somoclu/somoclu-1.6.1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=e8aef774e93fe47a990798e7771173a2

**Comment by arhuang** [comment]
Hi, I keep getting the import error: "Warning: training function cannot be imported. Only pre-trained maps can be analyzed." so wrap_train never gets imported from .somoclu_wrap and thus global name 'wrap_train' is not defined

**Comment by xgdgsc** [comment]
@arhuang How did you install?

**Comment by arhuang** [comment]
I first did it using pip and then the 1.6 version linked above.

**Comment by xgdgsc** [comment]
@arhuang What' s your platform and Python version?

**Comment by arhuang** [comment]
osx 10.11 python 2.7

**Comment by xgdgsc** [comment]
@arhuang Are you using the python installed by `homebrew` or system python? I tested the [wheel package](https://pypi.python.org/packages/6f/f7/03939347c04b265d07142c8566048086b9f56b780db8c04c0fdf9ed07893/somoclu-1.6.1-cp27-none-macosx_10_11_x86_64.whl#md5=50b19cf29b2e2567e21ea8135ac577e1) with the python installed by homebrew and it worked fine.

**Comment by arhuang** [comment]
I am using python installed by homebrew, is that wheel package the one installed with pip?

**Comment by xgdgsc** [comment]
@arhuang It should be. You can try downloading the wheel to make sure.

**Comment by arhuang** [comment]
Am I missing .somoclu_wrap? I get the warning both when i import somoclu and when i use train.

**Comment by xgdgsc** [comment]
@arhuang Can you find `_somoclu_wrap.so` under you `site-packages` directory?

**Comment by arhuang** [comment]
sorry where is the site-packages directory?

**Comment by arhuang** [comment]
I found a site packages directory in ~Library/Python/2.7/site-packages but it does not include somoclu

**Comment by arhuang** [comment]
I found somoclu_wrap.py in site packages but not somoclu_wrap.so

**Comment by arhuang** [comment]
oh wait sorry, I found somoclu_wrap.so

**Comment by arhuang** [comment]
ok sorry, I think the somoclu_wrap.so didn't install the first time, everything works now. Thanks for your help

**Comment by KevinAyuque** [comment]
I'm getting the same problem "Warning: training function cannot be imported. Only pre-trained maps can be analyzed." using Python 2.7 (default and virtualenv) on OSX El Capitan. Hopefully someone can help me. I tried installing directly from pip and the wheel package with no luck.

**Comment by xgdgsc** [comment]
@KevinAyuque Do you mean the system python by "default"? Have you tried the brew python?

**Comment by KevinAyuque** [comment]
I'm using the python located on /usr/local/bin/python which I think is the homebrew python.

**Comment by KevinAyuque** [comment]
I tried with python3 and still get the same problem.

**Comment by xgdgsc** [comment]
Which package did you install? The `so` file name is wrong. It should be:

```
Soul-MacBook-Pro:tests gsc$ ls /usr/local/lib/python3.5/site-packages/_somoclu*
-rwxr-xr-x  1 gsc  admin  84752 Mar 23 12:58 /usr/local/lib/python3.5/site-packages/_somoclu_wrap.cpython-35m-darwin.so
Soul-MacBook-Pro:tests gsc$ ls /usr/local/lib/python2.7/site-packages/_somoclu*
-rwxr-xr-x  1 gsc  admin  86476 May 10 18:57 /usr/local/lib/python2.7/site-packages/_somoclu_wrap.so
```

**Comment by KevinAyuque** [comment]
@xgdgsc I used this one (posted above) https://pypi.python.org/packages/6f/f7/03939347c04b265d07142c8566048086b9f56b780db8c04c0fdf9ed07893/somoclu-1.6.1-cp27-none-macosx_10_11_x86_64.whl#md5=50b19cf29b2e2567e21ea8135ac577e1 for the 2.7 and https://pypi.python.org/packages/3.5/s/somoclu/somoclu-1.6.1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=e8aef774e93fe47a990798e7771173a2 for 3.5

I installed it using pip:
pip3 install somoclu-1.6.1-cp35-cp35m-macosx_10_11_x86_64.whl

**Comment by xgdgsc** [comment]
I tried with the same packages and they install fine here. You can try changing the file names. Maybe there are something wrong with your pip.

**Comment by KevinAyuque** [comment]
I tried reinstalling again and this are the files I get:
  /usr/local/lib/python2.7/site-packages/_somoclu_wrap.so
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/somoclu-1.6.1.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/somoclu/__init__.py
  /usr/local/lib/python2.7/site-packages/somoclu/__init__.pyc
  /usr/local/lib/python2.7/site-packages/somoclu/somoclu_wrap.py
  /usr/local/lib/python2.7/site-packages/somoclu/somoclu_wrap.pyc
  /usr/local/lib/python2.7/site-packages/somoclu/train.py
  /usr/local/lib/python2.7/site-packages/somoclu/train.pyc

I also updated my pip to the latest (8.1.2) and still no luck. I'll keep trying and let you know if I find a solution. Thanks for the assistance.

**Comment by xgdgsc** [comment]
Have you installed `libiomp`?

**Comment by KevinAyuque** [comment]
@xgdgsc that solved it! thank you so much!

**Comment by kunal-ray** [comment]
I using python 2.7.10 on windows 10
I tried installing somoclu by pip as well as from https://github.com/peterwittek/somoclu/releases/tag/1.6
In both cases installation was fine but importing somoclu gives an error of training function cannot be imported.
Please help

**Comment by xgdgsc** [comment]
@kunal-ray Have you tried https://pypi.python.org/packages/72/39/cb5c9dc0724c285225abc539b02d0af77e6e619eb7aa73d0a4af9eab4216/somoclu-1.6.1-cp27-none-win_amd64.whl ?

**Comment by kunal-ray** [comment]
I just tried it, but that did not solve the problem. I am still getting the same warning of training function cannot be imported

**Comment by kunal-ray** [comment]
a

**Comment by xgdgsc** [comment]
Do you have `\site-packages\_somoclu_wrap.[YOUR ARCH].pyd` under your python directory?

**Comment by kunal-ray** [comment]
I have _somoclu_wrap.pyd

**Comment by xgdgsc** [comment]
Usually adding `MSVCP90.DLL` and `VCOMP90.DLL` would do.

**Comment by kunal-ray** [comment]
Where do I find them from? 
I understand they should go in C:\Windows\System32 or C:\Windows\SysWOW64.

**Comment by xgdgsc** [comment]
https://www.dll-files.com/

**Comment by kunal-ray** [comment]
Warning is gone, so I hope it is fine now. Thanks

**Comment by davidlamb** [comment]
I'm having the same problem with installing somoclu on Windows 10 Python 2.7 (using 32 bit). It gives me the same warning and then the error name 'wrap_train' is not defined. I have installed through pip using the whl as well as the executable. I've uninstalled through pip and just deleting the folder. I've installed Visual C++ 2008 express, as well as the redistributable. 

I've also tried it through winpython https://winpython.github.io/ (64 and 32 bit versions). I was surprised that didn't work and I get the same errors.

I tried anaconda and that did work. I tried copying the dll files that come with that version and paste them in the System32 folder to see if that would do it but it didn't.

Any other suggestions? Is there a way to test it with winpython?

**Comment by xgdgsc** [comment]
Is your Windows 10 32bit or 64bit?

**Comment by Apoorvakuril** [comment]
I am using  Windows 10 Python 2.7.11 (using 64 bit). It gives me the same warning and then the error name 'wrap_train' is not defined. Plz help. I installed using pip and wheel for somoclu - 1.7 and before that 1.6.1 too.

**Comment by xgdgsc** [comment]
@Apoorvakuril Have you tried adding some dlls as above comments said?

**Comment by BennSandoval** [comment]
For Mac users:  
is not valid: brew install libiomp
use this instead: brew install homebrew/boneyard/libiomp

**Comment by peterwittek** [comment]
@BennSandoval, thanks for this. If libiomp was migrated to the boneyard, it surely isn't a future-proof solution. As far as I understand, Xcode's clang still does not support OpenMP. On Linux with clang 3.9, the code compiles with OpenMP without any issue. Do you see a better way forward? I can't test it, but would [llvm](https://stackoverflow.com/questions/38971394/brew-install-clang-omp-not-working) work?

**Comment by BennSandoval** [comment]
@peterwittek I tried llvm and did not work.

**Comment by peterwittek** [comment]
Thanks for checking it.

**Comment by shaayaansayed** [comment]
Facing the same issue on linux machine with python 2.7, using the python installed by anaconda. I'm trying to use pip to install somoclu but getting the 'Warning: training function cannot be imported. Only pre-trained maps can be analyzed' error . Any idea what the issue could be?

**Comment by peterwittek** [comment]
You probably lack a compiler. Either install it from your distribution's repo, or install Anaconda's own by 'conda install gcc'.

**Comment by tomekzbrozek** [comment]
@peterwittek did you manage to fix it for Python 3.5, mac OS 64bit? I proceeded with all the tips listed above, and still get the error: 

"Warning: training function cannot be imported. Only pre-trained maps can be analyzed.
If you installed Somoclu with pip on OS X, this typically means missing libiomp. Please refer to the documentation and to this issue:
https://github.com/peterwittek/somoclu/issues/28"

**Comment by peterwittek** [comment]
The wheel file on PyPI was compiled with Python 3.6. Either upgrade your Python version, or go through the [instructions](https://somoclu.readthedocs.io/en/stable/download.html#build-on-mac-os-x) of how to compile it from scratch.

**Comment by xgdgsc** [comment]
Sorry currently there is no binary for macOS on pypi now since I have no access to a mac.

**Comment by festarju** [comment]
Hi, @xgdgsc & @peterwittek 
Thank you for your work!
I tried everything I could imagine, but I sill have problems with the import #83 :

> ImportError: failed to import (/home/bdalab/anaconda3/lib/python3.6/site-packages/somoclu-1.7.4-py3.6-linux-x86_64.egg/_somoclu_wrap.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm) 

> Warning: training function cannot be imported. Only pre-trained maps can be analyzed.

more info: [https://a.pomf.space/zilkxsyxitvy.htm](url)

Can you suggest something?

**Comment by xgdgsc** [comment]
This usually relates to glibc version, maybe you can try using system python.

**Comment by peterwittek** [comment]
That is precisely the problem. The system GCC and the one that Anaconda was compiled with are different. Either use the system Python or try the [experimental conda recipe](https://github.com/peterwittek/somoclu/issues/65#issuecomment-318843517).

**Comment by festarju** [comment]
Thank you @xgdgsc ! 
I switched to system python (with some downgrading of `zlib1g`...) and can now compile a binary for  CLI & `libsomoclu.so` (not the `_somoclu_wrap.cpython-36m-x86_64-linux-gnu.so`)
But what is the trick to get a python module (with `pip install somoclu` ?) that knows about **envvar** `CUDAHOME`?
In jupyter notebook, when
`som = somoclu.Somoclu(n_columns, n_rows, compactsupport=False, kerneltype=1)` 
I get `RuntimeError: Compiled without CUDA!`


**installed with pip:**
`~/.pyenv/versions/3.6.1/lib/python3.6/site-packages/somoclu-1.7.4-py3.6.egg-info$ cat installed-files.txt `
`../somoclu/__init__.py`
`../somoclu/somoclu_wrap.py`
`../somoclu/train.py`
`../somoclu/__pycache__/__init__.cpython-36.pyc`
`../somoclu/__pycache__/somoclu_wrap.cpython-36.pyc`
`../somoclu/__pycache__/train.cpython-36.pyc`
`../_somoclu_wrap.cpython-36m-x86_64-linux-gnu.so`
`dependency_links.txt`
`requires.txt`
`SOURCES.txt`
`PKG-INFO`
`top_level.txt`

**Comment by xgdgsc** [comment]
When you run `pip install somoclu` or `python setup.py install` ,  you should have the environment variable `CUDAHOME` set.

**Comment by festarju** [comment]
I belive I have **CUDAHOME** set:

`group8@bdalab-249:~/git2-somoclu$ python`
`Python 3.6.1 (default, Jul 30 2017, 15:00:21) `
`[GCC 5.4.0 20160609] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import os`
`>>> os.environ['CUDAHOME']`
`'/usr/local/cuda-8.0'`

here is the log from my `python ./setup.py install` 
[https://a.pomf.space/jwvjtqncqlnw.html](https://a.pomf.space/jwvjtqncqlnw.html)

BTW, this I found in setup.py and corrected:
`try:`
    `    #CUDA = find_cuda()`
    `    CUDA = None`
`except EnvironmentError:`
    `    CUDA = None`
    `    print("Proceeding without CUDA")`

**Comment by peterwittek** [comment]
The log looks fine to me. The CUDA compiler is verbose, but the output is a series of irrelevant warnings.

Please try the [conda recipe](https://github.com/peterwittek/somoclu/issues/65#issuecomment-318843517) that we are trying to put together. I just tried it, and if you set CUDAHOME, it compiles with GPU kernel and it works from Anaconda.

**Comment by Zub4ir** [comment]
I got this error on my fresh install of Windows 10. An easy fix is to download a "Visual C++ Redistributable for Visual Studio 2015" or newer. It contains the OpenMP libraries in an easy single click install.

**Comment by JimmyGao0204** [comment]
I have got the same error as follows:
![image](https://user-images.githubusercontent.com/14976770/59495644-55745e00-8ec2-11e9-89d3-c5df076246c1.png)
Using Windows 10 64 bit, python 3.5.2 and install somoclu via pip install somoclu.
Does anybody know how to fix this bug?Thank you very much.

**Comment by JimmyGao0204** [comment]
@xgdgsc I have not \site-packages\_somoclu_wrap.[YOUR ARCH].pyd under my python directory. I have try to add MSVCP90.DLL and VCOMP90.DLL  to C:\Windows\System32. But it didn't work. How should I fix this problem.
![image](https://user-images.githubusercontent.com/14976770/59573789-3276c380-90e7-11e9-87ae-f5a57398f195.png)
