### ISSUE TITLE
error in denseGPU code : _Block_Type_Is_Valid (pHead->nBlockUse) 

### ISSUE THREAD

**Issue by jturner65** [peterwittek/somoclu#32]
hello

i get the above error (_Block_Type_Is_Valid (pHead->nBlockUse) )  when i attempt to run the code with denseGPU enabled on the given rgbs.lrn file.  The error happens in trainOneEpochDenseGPU, at the end of the function, trying to delete[] bmus.

I am running windows 7, visual studio 2013, i have cuda 7.5, Microsoft mpi, my video card is an NVidia 680m (kepler card, gk104).  This is in a 64bit build, both debug and release - cuda dropped 32bit build support with cuda 7, afaik.

everything works fine with the denseCPU flag, just throwing that out there. :)

**Comment by xgdgsc** [comment]
This is an issue with memory allocation on windows. I will look into it.

**Comment by jturner65** [comment]
also, i forgot to add, for the columnMap array in io.cpp, i had to add a *sizeof(unsigned int) to all the array allocations or i got a similar error on columnMap's delete[].

**Comment by xgdgsc** [comment]
https://github.com/peterwittek/somoclu/commit/c2052d0f01b19e82693065cb009fcdbf91982b3e should fix it. I haven' t found why columnMap would have this issue.

**Comment by jturner65** [comment]
great, thanks!  i'll give it a shot and report back with what i find.

**Comment by jturner65** [comment]
yep, that did the trick.
