### ISSUE TITLE
BMU Mapping

### ISSUE THREAD

**Issue by mocofogic** [peterwittek/somoclu#33]
Hello,

I realized that in the .bm-output-files several input vectors can be associated with the same BMU. In this example one can see, that input vectors 2 and 3 are mapped to BMU (3,10) and 6 and 7 are mapped to BMU (2,49):
```
%50 50
%4616
0 49 17
1 47 12
2 3 10
3 3 10
4 49 2
5 0 11
6 2 49
7 2 49
8 0 11
9 4 0
10 11 4
...
```

 Is there a way to have one and only one input vector mapped to one BMU? I. e. can the algorithm map to the next best matching unit if an input vector was already mapped to a BMU?

**Comment by peterwittek** [comment]
Indirectly, yes. You have two options:

1. Increased the size of the map so you have more, possibly much more nodes than data points.
2. Initialize the map with PCA. The Python wrapper can do this natively, but it is not hard to do in general.

Perhaps a combination of the two will work.
