### ISSUE TITLE
Why can't I run train() many times?

### ISSUE THREAD

**Issue by oliviaguest** [peterwittek/somoclu#34]
When I run ```som.train()``` in Python after having previously trained a SOM I get the following error:

```
TypeError: Array must have 1 dimensions.  Given array has 2 dimensions
```

What am I doing wrongly?

**Comment by oliviaguest** [comment]
OK, so according to my code if I run ```som.update_data(data)``` even though data has not changed, it then is willing to continue training for me. I assume that wherever ```data``` is stored when ```som``` initialised it gets somehow consumed during a single call to ```som.train()```?

**Comment by peterwittek** [comment]
This is odd. The data is definitely not consumed. If it was float32, no copy is made and the pointer is passed to the C++ code. If type conversion is necessary, a new copy of type float32 is made, and the corresponding pointer is passed on. In either case, the C++ routines only *read* the array.

The pointer passing involves a fairly innocent reshaping to 1D on the Python side. Based on what you say, I conjecture that this reshaping is kept after the training. It should not be the case, but I would have to know more to address this. What is the exact error message?

**Comment by peterwittek** [comment]
I can reproduce it and confirm that this is a bug.

**Comment by peterwittek** [comment]
Commit 2aa4c27373a6ccda2e492b28a85feeb437e68d06 resolves this. Please try it.

**Comment by oliviaguest** [comment]
Amazing! Thank you!

**Comment by oliviaguest** [comment]
Hmm, so compiled it from github to check your fix (Iwas using pip version before). I am now getting this error when I call ```som.train()``` (the first time):

```
NameError: global name 'wrap_train' is not defined
```

**Comment by peterwittek** [comment]
This is probably due to the library not being compiled. When you import Somoclu, it should give you a warning to this end. If this is the case, only the visualization and file loading routines work, training does not. If you use the git version, this should get you going:

    ./autogen.sh
    ./configure --without-mpi
    make python
    cd src/Python
    python setup.py install --user --upgrade
