### ISSUE TITLE
Python save codebook?

### ISSUE THREAD

**Issue by Dringite** [peterwittek/somoclu#35]
How do you save the codebook and umatrix for future use? The documentation has no API for this.

**Comment by xgdgsc** [comment]
They can be saved to the `OUTPUT_PREFIX` with option -s 2:
```
-s NUMBER                Save interim files (default: 0):
                            0: Do not save interim files
                            1: Save U-matrix only
                            2: Also save codebook and best matching
```

**Comment by xgdgsc** [comment]
You can see there is `filename` parameter in view* functions http://somoclu.readthedocs.io/en/stable/reference.html .

**Comment by Dringite** [comment]
I was under the impression that was referring to the plot.

**Comment by peterwittek** [comment]
The filename option works for the U-matrix. If you want to save anything else -- the codebook or the BMUs -- these are completely standard numpy arrays, so you can use standard Python pickling or numpy saving routines. You can also save the U-matrix this way. The only thing to keep in mind is that the codebook is a 3-tensor. This works:

```python
import somoclu
import numpy as np
rows, columns = 30, 50
som = somoclu.Somoclu(columns, rows, data=np.random.rand(50, 2))
som.train(epochs=10)
np.savetxt("umatrix.txt", som.umatrix)
np.savetxt("codebook.txt", som.codebook.reshape((rows, columns*2)))
np.savetxt("bmus.txt", som.bmus)
```

**Comment by Dringite** [comment]
There appears to be a problem with savetxt codebook (typeerror mismatch)
But h5py works fine, savetxt probably has difficulty with higher dimensional tensors or something.

**Comment by peterwittek** [comment]
Good point. You probably want to use h5py anyway, as the codebook is typically in the range of a few gigabytes for larger maps and higher dimensions.

**Comment by Dringite** [comment]
This is somewhat unrelated but I am not really sure where else to ask, after training a "toroid" + "hexagonal" I find myself in a position where I want to append the BMUs to my dataset for further training via supervised learning.
However the nature of the BMUs makes that seem unwise, not as they currently are - since it wraps around the axis.
So in order to give the BMUs euclidean meaning I'm considering converting it to a Clifford torus (4 dimensional torus), does anyone have any better solution to this? The Clifford torus will give it euclidean meaning but somewhat eradicate the scale. I'm pretty sure that any minimum distance will remain minimum after conversion.
