### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Somoclu'

### ISSUE THREAD

**Issue by violivei** [peterwittek/somoclu#37]
Hello!

First of all, sorry if this is a stupid question, but I'm looking forward to working with somoclu and 
unfortunately I'm facing this issue when I compile one of the examples shown on the main page.

```
  File "somoclu.py", line 1, in <module>
    import somoclu
  File "C:\Projects\nlp-django-api\somoclu\somoclu.py", line 18, in <module>
    som = somoclu.Somoclu(n_columns, n_rows, data=data, maptype="planar",
AttributeError: 'module' object has no attribute 'Somoclu'
```

somoclu seems to be in site-packages folder. I'm not sure what exactly I'm missing.

Thanks in advance.

**Comment by peterwittek** [comment]
Could you try renaming the file to anything else? I think Python wants to import the file itself instead of the module.

**Comment by violivei** [comment]
Genius!! That was exactly it!
It works fine on Ubuntu, but on Windows I receive:

```
  File "C:\Python27\lib\site-packages\somoclu\train.py", line 181, in train
    wrap_train(np.ravel(self._data), epochs, self._n_columns, self._n_rows,
NameError: global name 'wrap_train' is not defined
```

**Comment by xgdgsc** [comment]
@violivei How did you install somoclu on Windows?

**Comment by violivei** [comment]
@xgdgsc 
just "pip install somoclu". I saw from the docs that you may face .dll issues, would that be it?
I also installed all python dependencies such as numpy and I ran everything using ipython + notebook as well.

**Comment by violivei** [comment]
Actually, there is already a question about that issue. I'm going to take a look at that first.
Thanks for the attention.
