### ISSUE TITLE
Visual Studio 2015 - project load failed

### ISSUE THREAD

**Issue by pegasone** [peterwittek/somoclu#41]
Project load fails when trying to open src\Windows\somoclu\somoclu.sln (1.6.1) in Visual Studio Community 2015 Update 3 on Windows 10. The error message in Solution Explorer is,: "The project requires user input. Reload the project for more information." What am I missing?

**Comment by xgdgsc** [comment]
Have you tried reloading the project as the message says?

**Comment by pegasone** [comment]
Yes, that's the first thing that I did.

**Comment by xgdgsc** [comment]
Does the Output console show CUDA version not found?

**Comment by pegasone** [comment]
CUDA is not installed to my system (using an AMD GPU). I just want to build a console version of somoclu on my machine. The python version seems to work as expected and apparently can use all 8 logical processors, I would like to be able to do the same from a command prompt.

**Comment by xgdgsc** [comment]
Then you can try removing the above mentioned sections from `somoclu.vcxproj`.

**Comment by pegasone** [comment]
After deleting those sections I can load the solution/project. Build fails with two errors: 

C3016: 'som_y': index variable in OpenMP 'for' statement must have signed integral type

C2371: 'int8_t': redefinition; different basic types

I am using the Microsoft MPI SDK v7.1

**Comment by xgdgsc** [comment]
Have you deleted the `CUDA` macro in project settings?

**Comment by pegasone** [comment]
I deleted all cusa-related information in .vcxproj; the errors persist.

**Comment by pegasone** [comment]
Well, now it builds with no errors but it doesn't run. Three threads exit with code 1.

**Comment by xgdgsc** [comment]
@pegasone How did you run it? Did you give it any arguments? I tried here with no run problem.

**Comment by pegasone** [comment]
Yes, actually it fails when run in VS2015 w/o parameters. The error message "Incorrect number of mandatory parameters", as well as other informative messages, are shown when run at the command prompt. Thanks!

**Comment by greatychaudhary** [comment]
The project requires user input. Reload the project for more information." What am I missing?

**Comment by xgdgsc** [comment]
You may need to check the vcxproj file content to see if versions and paths match you installation.
