### ISSUE TITLE
training function cannot be imported

### ISSUE THREAD

**Issue by kunal-ray** [peterwittek/somoclu#42]
Hello,
I am using 64 bit Python 2.7.10 in Windows 10.
I installed somoclu by typing pip install somoclu in cmd.
It installed without any error message.
I typed import somoclu
The prompt gave warning: Warning: training function cannot be imported. Only pre-trained maps can be analyzed.

I found a bug report but it talks only about IOS and Ubuntu, so not sure as to what I need to do in my case to resolve the issue.

**Comment by peterwittek** [comment]
This is the same as #28

**Comment by miracleMITSUWO** [comment]
Hello,
Resentlly I replaced my PC in Python 3.7.1 in Windows 10 64bit. Also in VS2017 community.
So, I install Somoclu1.7.5 and also installed Microsoft Visual C++ 2008 SP1 Redistributable Package for reported DLL issue.
But I confermed forrwing massage and cannot som traning; 
Warning: the binary library cannot be imported. You cannot train maps, but you can load and analyze ones that you have already saved.
If you installed Somoclu with pip on Windows, this typically means missing DLLs. Please refer to the documentation.

Is it nessesary to install Visual Studio 2008 Express? Or  disribute whl package for python3.7 soon?
I really know just out on DLL file is not solve this problem.

I'd appreciate if you could answer these questions.

**Comment by xgdgsc** [comment]
Might be easier try to compile the source code.

**Comment by miracleMITSUWO** [comment]
That is very helpful!!
I also tried 'python setup.py install', but did not work...
