### ISSUE TITLE
Python with CUDA support

### ISSUE THREAD

**Issue by amirsani** [peterwittek/somoclu#49]
I can't seem to get CUDA support enabled in Python. 

I run the following series of commands:
export CUDAHOME=/usr/local/cuda-7.5/
./autogen.sh
./configure --with-cuda=/usr/local/cuda-7.5  -> Cuda support = yes here
make
sudo make install
make python
cd src/Python/
sudo python setup.py install

and then it outputs this as the first line:
Proceeding without CUDA

I run the example and only get CPU time,
n_rows, n_columns = 100, 160
som = somoclu.Somoclu(n_columns, n_rows, data=data, kerneltype=1)
%time som.train()
CPU times: user 34.9 s, sys: 104 ms, total: 35 s
Wall time: 19.5 s

any ideas on how to get CUDA working?

Thank you,

Amir

**Comment by peterwittek** [comment]
The configure option is for the command line version. The Python setup script detects CUDA through the CUDAHOME environment variable. It is described in the [documentation](https://somoclu.readthedocs.io/en/stable/download.html) under the section Build with CUDA support on Linux and OS X.
