### ISSUE TITLE
How can I set the default GPU?

### ISSUE THREAD

**Issue by amirsani** [peterwittek/somoclu#50]
I have two GPU. How can I set the default GPU?

Thank you,

Amir

**Comment by peterwittek** [comment]
The Nvidia driver picks the better GPU for CUDA calculations. I belive it is the one that shows up first when issuing `nvidia-smi -q`. I am not sure if the driver lets you switch at the OS level. Somoclu can use both GPUs through the command-line interface if you compile it with MPI, but if you use it in a single-process execution or through the Python interface, it will use the GPU provided by the Nvidia driver and the CUDA runtime -- there is no option to change this.
