### ISSUE TITLE
make fail on CentoOS

### ISSUE THREAD

**Issue by apastore** [peterwittek/somoclu#52]
Missing include cstring ?

make all
make -C src all
make[1]: Entering directory `/cbio/cslab/home/pastore/bin/somoclu/src'
mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DMPICH_IGNORE_CXX_SEEK -DCLI -I/opt/mpich2/gcc/eth/include -I. -I.. -o somoclu.o -c ./somoclu.cpp
./somoclu.cpp: In function ‘int main(int, char**)’:
./somoclu.cpp:312:50: error: ‘strcpy’ was not declared in this scope
         strcpy(inFilenameCStr, inFilename.c_str());
                                                  ^
./somoclu.cpp:319:44: error: ‘strcpy’ was not declared in this scope
         strcpy(mapTypeCStr, mapType.c_str());
                                            ^
./somoclu.cpp:326:46: error: ‘strcpy’ was not declared in this scope
         strcpy(gridTypeCStr, gridType.c_str());
                                              ^
make[1]: *** [somoclu.o] Error 1
make[1]: Leaving directory `/cbio/cslab/home/pastore/bin/somoclu/src'
make: *** [all] Error 2

./configure --prefix=/cbio/cslab/home/pastore/bin/
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to support OpenMP... -fopenmp
checking for nvcc... yes
checking for mpic++... mpic++
checking for MPI directory... /opt/mpich2/gcc/eth
/usr /usr/lib/openmpi /cbio/cslab/home/pastore/nobackup/bcbio /opt/mpich2/gcc/eth /opt/gnu/gcc/4.8.1 /opt/gnu/gcc/4.8.1 /opt/gnu/gmp /opt/gnu/mpc /opt/gnu/mpfr
checking how to run the C++ preprocessor... g++ -E
checking whether we can preprocess mpi.h... yes
checking whether we can compile mpi.h... yes
checking whether special compile flag for MPICH is required... yes

Adding -DMPICH_IGNORE_CXX_SEEK to MPICH compilations

configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged

 Somoclu Version 1.6.2

 Prefix: /cbio/cslab/home/pastore/bin.
 Compiler: mpic++ -fPIC -fopenmp -O3 -ffast-math -march=native -DMPICH_IGNORE_CXX_SEEK -I/opt/mpich2/gcc/eth/include -L/opt/mpich2/gcc/eth/lib -lmpi

 Package features:
   OpenMP enabled: yes
   MPI enabled: yes
   CUDA enabled: yes

 Now type 'make [<target>]'
   where the optional <target> is:
     all                - build all binaries
     install            - install everything

--------------------------------------------------

**Comment by xgdgsc** [comment]
Would just adding <cstring> fix it?

**Comment by apastore** [comment]
It fix the compile issues…. not the Running issues… unfortunately that is still there also after Rcpp update

**Comment by peterwittek** [comment]
I am a bit confused. Are you trying to get the R version or the MPI version running? I can see you are using mpich, which we did not test in a long while, so apologies for having trouble with that.

**Comment by apastore** [comment]
I am just trying to have it running on R

**Comment by peterwittek** [comment]
Then you can rely on the R build system and you do not need to run the configure script, and especially not MPI.
