### ISSUE TITLE
How to use multi core in R

### ISSUE THREAD

**Issue by apastore** [peterwittek/somoclu#53]
Just a question, how you configure the core number in R?
OMP_NUM_THREADS?
Thanks!

**Comment by peterwittek** [comment]
That should work. Single-node multithreading is via OpenMP.

**Comment by apastore** [comment]
as a R variable? could you please add and example in the R interface test ?

Thanks!

**Comment by peterwittek** [comment]
I am afraid this really is external to Somoclu. [This](https://wrathematics.github.io/RparallelGuide/) write-up tells you how it can be done; see Section 5.2. Basically, you have to set the environment variable prior to starting R. If you don't set the environment variable, all available cores will be used.

**Comment by apastore** [comment]
Ok got it
