### ISSUE TITLE
[Python] sklearn warns with init=PCA

### ISSUE THREAD

**Issue by yoch** [peterwittek/somoclu#58]
> Warning (from warnings module):
>   File "C:\Users\yoch\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\deprecation.py", line 52
>     warnings.warn(msg, category=DeprecationWarning)
> DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.

**Comment by peterwittek** [comment]
Commit cceef73d721a99535853a4a535d505c7da609321 solves this. Please try it.

**Comment by yoch** [comment]
It's good with 0.18, but it breaks in previous versions of sklearn.

Maybe you can use a patch like : 

```python
from functools import partial

if sklearn.__version__ >= '0.18':
    from sklearn.decomposition import PCA
    PCA = partial(PCA, svd_solver="randomized")
else:
    from sklearn.decomposition import RandomizedPCA as PCA

# and later
pca = PCA(n_components=2)
```

**Comment by peterwittek** [comment]
Good point. Commit 7793f6be320867ec69add61c6981e6fe99fa48b9 copies this almost verbatim, only replacing the version check with a try-catch block.

**Comment by yoch** [comment]
I think commit 7793f6b will raise exception in version 0.17 and prior, because `PCA` exists but don't accept 'svd_solver' as keyword.

**Comment by yoch** [comment]
Excellent !
