### ISSUE TITLE
Curious artefacts in codebok with MNIST data

### ISSUE THREAD

**Issue by yoch** [peterwittek/somoclu#59]
Hello,

Thank you for your great work !

I made some experiments with somoclu on MNIST dataset (handwritten digits), and I noticed that there are curious artefacts in the resulting codebook.

Here a visualization of the trained codebook, and result from my own implementation for comparison :

![somoclu](https://cloud.githubusercontent.com/assets/795960/19889327/f31b73d6-a03c-11e6-9efd-982f17cc98f1.png)
![som](https://cloud.githubusercontent.com/assets/795960/19889328/f3221376-a03c-11e6-8fca-a27e056285c9.png)

Two remarks : 
- there are strange artifacts (and sometimes negatives values) at the images corners
- somoclu produces significantly less sharp pictures (it seems this is simply because negative values are present in the codebook)

The only significant difference I can see between implementations is that mine use online training.

---

Here my code for this experiment : 

```python
import numpy as np
import matplotlib.pyplot as pl
from som import SOM     # my implementation
from somoclu import Somoclu
from mnist import load_mnist


H, W = 10, 15
E = 10
A = 0.3
R = 5
SHAPE = (12,12)


pl.rcParams.update(pl.rcParamsDefault)
pl.gray()


def plot_map(codebook, shape=SHAPE, filename=None):
    map_ = np.vstack([np.hstack([codebook[i,j].reshape(shape) for j in range(W)])
                      for i in range(H)])
    pl.matshow(map_)
    if filename is not None:
        pl.savefig(filename)
    else:
        pl.show()

# load MNIST (5000 first ones)
train_data, _ = load_mnist(dataset='training', zoom=0.5, crop=2)
data = train_data[:5000] / 255


som1 = Somoclu(W, H, data)
som2 = SOM(H, W, len(data[0]), verbose=False)


som1.train(epochs=E, radius0=R, scale0=A)
som2.train(data, E * len(data), A, R)

plot_map(som1.codebook, filename='somoclu.png')
plot_map(som2.net, filename='SOM.png')
```

**Comment by peterwittek** [comment]
This is troubling. Are you sure the neighbourhood functions are the same? By default, Somoclu uses a Gaussian neighbourhood in which the updates are not strictly cut off at the radius: this is to allow smoother maps, which, in your case, might explain the grey background. You could try this:
```python
som1 = Somoclu(W, H, data, compactsupport=True)
```
Alternatively, you could try the bubble neighbourhood, which always results in a compact support for the update.

I cannot think of an explanation for the strange artifacts, though.

BTW, which MNIST loader are you using?

**Comment by yoch** [comment]
I also use gaussian neighborhood function.

Here my custom [MNIST loader](https://gitlab.com/edf6rnea/som/blob/master/mnist.py) (it needs .gz files from the original database).

**Comment by peterwittek** [comment]
Thanks. I played around a bit and figured it out. If you use the PCA init, all is fine. The trouble was that with random init, you get this grey average, and if the update to the codebook was a zero, it was not written back. It was a bug. I will push the fix for all kernels in a short while.

**Comment by peterwittek** [comment]
Commit a46c488ffbb0b9d247c799e973afa1291fd7653e should fix this. Please try it. The artifacts also go away.

**Comment by yoch** [comment]
All it's OK now, thank tou very much !

**Comment by peterwittek** [comment]
And thanks for the bug report.
