### ISSUE TITLE
The ``configure'' script cannot find ``mpi.h'' even though it is installed

### ISSUE THREAD

**Issue by usptact** [peterwittek/somoclu#6]
The "configure" script fails to find the "mpi.h" include file. I am pretty sure that the MPI has been installed correctly.

What steps can be taken to debug and resolve the issue?

**Comment by xgdgsc** [comment]
What OS is it and how did you install MPI?

**Comment by peterwittek** [comment]
Please also look into the relevant flags of the configure script to fine-tune the location of the MPI directories:

    --with-mpi=MPIROOT      Use MPI root directory.
    --with-mpi-compilers=DIR or --with-mpi-compilers=yes
                              use MPI compiler (mpicxx) found in directory DIR, or
                              in your PATH if =yes
    --with-mpi-incdir=DIR   MPI include directory [default MPIROOT/include]
    --with-mpi-libdir=DIR   MPI library directory [default MPIROOT/lib]

**Comment by usptact** [comment]
Thanks for replies. I tried under Debian 7.0 and Ubuntu 14.04. I installed the mpich packages (dev versions as well) from the software repository. I checked that the system include directories actually have the mpi.h file. This is how I was certain (more or less) that MPI has been installed.

Do you need more details?

**Comment by peterwittek** [comment]
MPICH is a bit quirkier than, say, OpenMPI, but I compiled and ran Somoclu with it before. What do you get for ``find /usr -name mpi.h``?

In any case, please note that MPI is required if you want to run it on a cluster. If you only want to run it on a multicore machine, then that level of parallelism is taken care of by OpenMP, so you might not need MPI at all.

**Comment by xgdgsc** [comment]
@usptact I just tried in a ubuntu 14.04 machine. 
Installing mpich with:
```
apt install mpich
```
and run the configure script with:
```
./configure --with-mpi=/usr/
```
works.

**Comment by usptact** [comment]
The ``--with-mpi=/usr/'' parameter was the key! Everything compiles and runs on both machines! Thanks for all your work and help with this issue!
