### ISSUE TITLE
problem with sparse data

### ISSUE THREAD

**Issue by yoch** [peterwittek/somoclu#63]
I compared the learning results on the same data (from MNIST) in both dense and sparse mode, the results are surprising and suggest a bug in the sparse version.

*The sparse version*
![sparse version](http://i.imgur.com/5LSOkRb.png)

*The dense version*
![dense version](http://i.imgur.com/HqQUK4Q.png)

Clearly there are ouliers in the codebook. I looked for the bug in the code but I did not find anything.

**Comment by peterwittek** [comment]
My conjecture is that the file is not read correctly -- the sparse file reader is super-stupid. Could you upload the exact file you are trying to load?

**Comment by yoch** [comment]
You're right, labelled data cause troubles in `readSparseMatrixChunk()`.

I've corrected this problem for me with this patch, but I admit that the parsing code can be cleaner, so I hesitate to make a pull request.

```cpp
    svm_node **x_matrix = new svm_node *[nRowsToRead];
    for(unsigned int i = 0; i < nRowsToRead; ) {
        getline(file, line);
        if (line[0] == '#') {
            continue;
        }
        stringstream tmplinestream(line);
        string value;
        int elements = 0;
        bool label = false;
        // count values
        while(getline(tmplinestream, value, ' ')) {
            // skip labels
            if (elements==0 && label==false && value.find(':') == string::npos)
            {
                label=true;
                continue;
            }
            elements++;
        }
        x_matrix[i] = new svm_node[elements+1];  // To account for the closing dummy node in the row
        stringstream linestream(line);
        if (label) // skip label
            linestream >> value; // skip the label
        int j = 0;
        while (1) {
            char sep;
            int idx;
            float val;
            linestream >> idx >> sep >> val;
            if (linestream.fail())
                break;
            //assert(sep==':');
            x_matrix[i][j].index = idx;
            x_matrix[i][j].value = val;
            j++;
        }
        //assert(j==elements);
        x_matrix[i][j].index = -1;
        i++;
    }
```

**Comment by peterwittek** [comment]
I tested it and it works fine with the included sparse example (rgbs.svm). This is really ancient code and I feel little inspiration to make glitteringly beautiful improvements, so I would welcome your PR.

**Comment by peterwittek** [comment]
PR #64 solves this.
