### ISSUE TITLE
How Can I get the cluster number or class for an specific data point?

### ISSUE THREAD

**Issue by BennSandoval** [peterwittek/somoclu#66]
After:
som = somoclu.Somoclu(n_columns, n_rows, data=data, maptype="toroid", initialization="pca")
som.train()
som.cluster()
som.view_umatrix(bestmatches=True)

How Can I get the cluster number or class for an specific data point like data[0]?

**Comment by peterwittek** [comment]
After calling `som.cluster`, the 2D array `som.clusters` holds the cluster information for each node. Match that with `som.bmu`, and you have the cluster number for each data point. Something like this:

```python
k = 0  # The data instance you are interested in 
som.clusters[som.bmus[k, 1], som.bmus[k, 0]]
```

**Comment by BennSandoval** [comment]
Awesome!! Thanks.
