### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by espg** [peterwittek/somoclu#70]
Any possibility to have a training progress callback _a la_ tensor board or tqdm? Would really help with scoping models to know even order of magnitude for runtime (i.e., hours versus weeks)...

**Comment by peterwittek** [comment]
Printing out a progress bar was exterminated because of the R version: the CRAN maintainers insist that the low-level C/C++ functions should not have any input or output. The high-level interfaces only get any kind of information once training is completed on all epochs, so that rules out the straightforward use of a simple solution like tqdm.

I see two ways forward (add more if you can think of better ones):

1. Add a progress bar in the C++-level code, subject to a verbosity parameter passed from the interface. This section of the code must be subject to macros that disable it when R compiles it. This solution is fast and efficient, but I conjecture that it would be hell to get it right with printing in a Jupyter notebook.
2. Manually break up the training to epoch by epoch. With the current version, it is easily done (issue #57 and see also commit 046e3d30df55e4e55afa23b445000829e0016c60). Then you could insert something like tqdm. This solution has quite a bit of overhead, especially for the GPU version, as it involves many memory copies behind the hood. On the other hand, different flavours of Python, IPython, and Jupyter will print things nicely, or at least the responsibility lies with a 3rd party.

**Comment by espg** [comment]
I think the first option is probably the way to go-- Epochs could already be days depending, so having an update on how long the time step 't' takes (and how many time steps are being executed) would be really useful. Also, having a verbosity flag is equally pertinent in the command line case as for the python interface. If there were a verbosity flag, I don't think that you'd need to worry to much about getting it to print in python or jupyter... it could print to standard output in the terminal that launched the notebook (tensorflow prints GPU memory usage to terminal rather than the python interface itself). I'd say that if you already had a progress bar pre-R in the C++ code, just enabling it via a verbosity flag would be awesome!

Another option for Epoch level training information might be to write the pertinent information (i.e., quantization error, start end time) to an external log file. This is actually how tensor board gets it's info for the web monitoring interface, so I suspect that it might even be possible to use it...

**Comment by peterwittek** [comment]
Actually, the progress bar is still there if you compile the code with MPI enabled. Then even if you run it on a single machine, it will display the progress epoch by epoch. I can look into it next week to add a verbosity parameter across all the interfaces (R exempted) and have this progress bar displayed.

I am a bit more reluctant to create an intricate logging system. I definitely do not want to introduce any dependency in the C++ code -- compilation was sufficiently difficult to get right as it is. After all, it works across the three major platforms, and with four high-level wrappers. The cheap option is to pipe the output somewhere, which then you can display the way you want it.

**Comment by peterwittek** [comment]
Commit ac95a7ba65f0d62b0374bf5dbbf03f9cab9f1866 introduces the verbosity parameter across all interfaces except R. As expected, it does not work from Jupyter, but this is completely external to Somoclu; see issue ipython/ipython#1230. In any case, please try it.

**Comment by espg** [comment]
Thanks for doing this--I'm working on getting this installed on a cluster to test out, I'll let you know how the progress bar works either tomorrow or Monday

**Comment by espg** [comment]
Alright, I had a chance to install and look at this, and ran into a few issues. First, I installed the most recent commit, 42cb65d, that updated the U-matrix calcs to be parallelized. That update builds, and installs--but gives the following on import in python:

> Warning: training function cannot be imported. Only pre-trained maps can be analyzed.

Backtracking to commit ac95a7b, I can install and import without problems. However, when I try to run a model, I get the following error:

` som.train(data=data[:10000])
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/local/lib/python3.6/site-packages/somoclu-1.7.3-py3.6.egg/somoclu/train.py", line 218, in  train
     self.umatrix)
 TypeError: train() takes exactly 21 arguments (22 given)
`

I ran into this trying to run with my specific model and the verbosity parameter; but falling back to the basic example in the documentation gives the same error:

`c1 = np.random.rand(50, 3)/5
c2 = (0.6, 0.1, 0.05) + np.random.rand(50, 3)/5
c3 = (0.4, 0.1, 0.7) + np.random.rand(50, 3)/5
data = np.float32(np.concatenate((c1, c2, c3)))
colors = ["red"] * 50
colors.extend(["green"] * 50)
colors.extend(["blue"] * 50)
n_rows, n_columns = 100, 160
som = somoclu.Somoclu(n_columns, n_rows, data=data, compactsupport=False)
Warning: passing the data in the constructor is deprecated.
som.train()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/somoclu-1.7.3-py3.6.egg/somoclu/train.py", line 218, in train
    self.umatrix)
TypeError: train() takes exactly 21 arguments (22 given)`

...it looks like a constructor somewhere hasn't been updated to take the verbosity parameter. I tried to track down where, but the wrap_train function passes things off to swig, and I don't see anything in somoclu_wrap.py that explicitly lists the parameters, so I'm not sure if the fix is in the python code or the underlying compiled code that generates _somoclu_wrap.so

**Comment by peterwittek** [comment]
I tried the latest commit and it works just fine. Can you tell me the exact steps you did? This should work:

```bash
git clone https://github.com/peterwittek/somoclu
cd somoclu
./autogen.sh
./configure
make python
cd src/Python
python setup.py install
```

**Comment by espg** [comment]
So, the steps that you list work fine...as long as I don't have mpi installed or flagged as an option in configure. There's no errors in the install part, but with MPI, the install isn't usable...I get the same 

`Warning: training function cannot be imported. Only pre-trained maps can be analyzed.` error as in my last post. Digging a bit deeper, there's a pretty specific error in the _somoclu_wrap.so file: 

`ImportError: /home/grigsbye/scripts/lib/python3.5/site-packages/somoclu-1.7.3-py3.5-linux-x86_64.egg/_somoclu_wrap.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __kmpc_ok_to_fork`

 ...or if you prefer, the same error in iPython: 

> In [21]: from somoclu import somoclu_wrap
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> /home/grigsbye/scripts/lib/python3.5/site-packages/somoclu-1.7.3-py3.5-linux-x86_64.egg/somoclu/somoclu_wrap.py in swig_import_helper()
>      13         try:
> ---> 14             return importlib.import_module(mname)
>      15         except ImportError:
> 
> /curc/sw/python/3.5.1/lib/python3.5/importlib/__init__.py in import_module(name, package)
>     125             level += 1
> --> 126     return _bootstrap._gcd_import(name[level:], package, level)
>     127 
> 
> /curc/sw/python/3.5.1/lib/python3.5/importlib/_bootstrap.py in _gcd_import(name, package, level)
> 
> /curc/sw/python/3.5.1/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)
> 
> /curc/sw/python/3.5.1/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)
> 
> ImportError: No module named 'somoclu._somoclu_wrap'
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError                               Traceback (most recent call last)
> <ipython-input-21-7089986df0c1> in <module>()
> ----> 1 from somoclu import somoclu_wrap
> 
> /home/grigsbye/scripts/lib/python3.5/site-packages/somoclu-1.7.3-py3.5-linux-x86_64.egg/somoclu/somoclu_wrap.py in <module>()
>      15         except ImportError:
>      16             return importlib.import_module('_somoclu_wrap')
> ---> 17     _somoclu_wrap = swig_import_helper()
>      18     del swig_import_helper
>      19 elif _swig_python_version_info >= (2, 6, 0):
> 
> /home/grigsbye/scripts/lib/python3.5/site-packages/somoclu-1.7.3-py3.5-linux-x86_64.egg/somoclu/somoclu_wrap.py in swig_import_helper()
>      14             return importlib.import_module(mname)
>      15         except ImportError:
> ---> 16             return importlib.import_module('_somoclu_wrap')
>      17     _somoclu_wrap = swig_import_helper()
>      18     del swig_import_helper
> 
> /curc/sw/python/3.5.1/lib/python3.5/importlib/__init__.py in import_module(name, package)
>     124                 break
>     125             level += 1
> --> 126     return _bootstrap._gcd_import(name[level:], package, level)
>     127 
>     128 
> 
> ImportError: /home/grigsbye/scripts/lib/python3.5/site-packages/somoclu-1.7.3-py3.5-linux-x86_64.egg/_somoclu_wrap.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __kmpc_ok_to_fork

The error on importing / with the __kmpc_ok_to_fork symbol presented on a cluster install, that has a fairly clean interface for building software; here's my exact build setup:

activeList = {
  ["boost"] = "1.61.0",
  ["impi"] = "5.1.3.210",
  ["intel"] = "16.0.3",
  ["perl"] = "5.24.0",
  ["python"] = "3.5.1",
  ["swig"] = "3.0.12",
}

...where intel is the intel compilers and version, and imp is the intel implementation of mpi.

I also tried this with GCC and openmpi on a vanilla RedHat install and ran into the same issue of not being able to import the training function.

I did try this without mpi, and things worked fine and the progress bar showed up without error (showing at the epoch level), but anything with mpi has not worked. I also installed a prior version from before the verbosity change, and ran into the same issue with mpi-- so whatever the issue is, it's likely somewhere else in the codebase and not related to the verbosity flag per se... When I submitted this earlier, I wasn't using MPI at all, but trying to get somoclu setup with MPI to test the progress bar, and also trying to migrate to a cluster instead of my desktop to run models has just showed me that I can't get somoclu to work with MPI enabled...

**Comment by peterwittek** [comment]
This is because the Python wrapper cannot use MPI. You either compile it with MPI and use Somoclu from the command line with `mpirun`, or you compile it without MPI, and then you can use the command line, or any of the wrappers. What the error message hints at is that you can do your training with the MPI-compiled version, and then read the files from Python to study the map.
