### ISSUE TITLE
a map in a 'textual format' in python

### ISSUE THREAD

**Issue by kroham** [peterwittek/somoclu#71]
Hello,

is there a function/method that returns a textual representation of a map (like to_string or something) in the python implementation? or the only way to examine the map is to look at the plot? I would like to examine the instances one by one (which area on the map they ended up in) but I have thousands of them :( It would be easier to have them in a list (per area) or something.

Thank you very much in advance. Regards

**Comment by peterwittek** [comment]
Are you talking about the BMUs?
```
n_rows, n_columns = 30, 50
som = somoclu.Somoclu(n_columns, n_rows)
som.train(data=np.random.rand(50, 2))
print(som.bmus)
```
Then you can organize them in areas as you like.

**Comment by kroham** [comment]
yes, but bmus doesn't give the information about the placement of the units on the map (the proximity between the units I mean), how do I group them in areas? by clustering?

My problem is that I do not want to specify the number of clusters, because that is exactly what I want to learn from the map: how many distinct groups there are.
