### ISSUE TITLE
view_activation_map : XA and XB must have the same number of columns

### ISSUE THREAD

**Issue by passionato** [peterwittek/somoclu#75]
Hi,
I am trying to produce an `view_activation_map` of my SOM, however I get a confusing error.

Here is my data example: https://pastebin.com/YJmwSsFt

**the code:**
```
n_rows, n_columns = 32, 32
som = somoclu.Somoclu(n_columns, n_rows, data=data_dump, maptype="toroid", gridtype="rectangular")
som.train(data_dump)
labels = range(data_dump.shape[0])
som.view_umatrix(bestmatches=True, bestmatchcolors=colors, labels=labels)
surf_state = som.get_surface_state()
my_bmus = som0.get_bmus(surf_state)
som.view_activation_map(surf_state, labels=labels)
```

**the error:**
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-208-9330619bbc55> in <module>()
----> 1 som0.view_activation_map(dot, labels=labels)

/usr/local/lib/python2.7/dist-packages/somoclu/train.pyc in view_activation_map(self, data_vector, data_index, activation_map, figsize, colormap, colorbar, bestmatches, bestmatchcolors, labels, zoom, filename)
    374                                                   self.codebook.shape[1],
    375                                                   self.codebook.shape[2])),
--> 376                            w, 'euclidean').T
    377             matrix.shape = (self.codebook.shape[0], self.codebook.shape[1])
    378         else:

/usr/lib/python2.7/dist-packages/scipy/spatial/distance.pyc in cdist(XA, XB, metric, p, V, VI, w)
   2069         raise ValueError('XB must be a 2-dimensional array.')
   2070     if s[1] != sB[1]:
-> 2071         raise ValueError('XA and XB must have the same number of columns '
   2072                          '(i.e. feature dimension.)')
   2073 

ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)


```
my final goal is to plot the distance map as the background, like here:
https://github.com/JustGlowing/minisom/blob/master/examples/example_iris.py#L25
unless it is already being done somewhere in somoclu??

I have also a side question:
what is the difference between
```
som = somoclu.Somoclu(n_columns, n_rows, data=data_dump, maptype="toroid", gridtype="rectangular")
som.train(data_dump)
```
and
```
som = somoclu.Somoclu(n_columns, n_rows, maptype="toroid", gridtype="rectangular")
som.train(data_dump)
```
??
In the second one the data is not provided when initializing the somoclu. What is the difference if we provide it twice? once in somoclu and secondin the training?

**Comment by peterwittek** [comment]
You are supplying the wrong data to `view_activation_map`. It expects either a single data instance or an index of a data instance in the training set.

There is no difference in where you pass data. Previously, we passed in the constructor, but it makes sense to pass it in `train`. We kept the older interface for compatibility.

**Comment by peterwittek** [comment]
I looked at the example in Minisom. I am wondering, isn't the `distance_map()` the same as `view_umatrix()`? It is essentially an average distance of the weight vectors visualized.

**Comment by passionato** [comment]
thanks for the answers and comments.
Actually, the minisom produces the distance map for the whole dataset (e.x. `plt.pcolor(som.distance_map().T, cmap='bone')` ), so if I want to see the heatmap for the whole dataset in the somoclu, apparently I can't, I have to subset a vector of the dataset, if i understood it correctly.

**Comment by peterwittek** [comment]
Honestly, I do not understand this. The distance map for the whole dataset is a rank-3 tensor. I checked the code of minisom, and I believe my interpretation of the method `distance_map()` is correct:

```python
def distance_map(self):
    """ Returns the distance map of the weights.
        Each cell is the normalised sum of the distances between a neuron and its neighbours.
    """
    um = zeros((self.weights.shape[0], self.weights.shape[1]))
    it = nditer(um, flags=['multi_index'])
    while not it.finished:
        for ii in range(it.multi_index[0]-1, it.multi_index[0]+2):
            for jj in range(it.multi_index[1]-1, it.multi_index[1]+2):
                if ii >= 0 and ii < self.weights.shape[0] and jj >= 0 and jj < self.weights.shape[1]:
                    um[it.multi_index] += fast_norm(self.weights[ii, jj, :]-self.weights[it.multi_index])
        it.iternext()
    um = um/um.max()
    return um
```
This is just the U-matrix as I suspected, it has nothing to do with the data points.
