### ISSUE TITLE
Use a non-deterministic random seed

### ISSUE THREAD

**Issue by yoch** [peterwittek/somoclu#76]
Currently, when random codebook initialization is required , [the random seed used](https://github.com/peterwittek/somoclu/blob/ac95a7ba65f0d62b0374bf5dbbf03f9cab9f1866/src/somoclu.cpp#L429) by `srand` is 0 (at least if the user not have R), making the algorithm deterministic.

It should be a good idea to add an option to control that (ie. to give the seed, and possibly using a non-deterministic one by defaut).

**Comment by peterwittek** [comment]
This was a bug. Commit 2dec98c1e0cb30a4642b85ead027562965a73796 fixes it. Deterministic codebooks can easily be created and passed by the user. Thanks for reporting it.

**Comment by yoch** [comment]
This commit don't fixes the second call to `initializeCodebook` in somoclu.cpp (linked above). It seems this one is used with the standalone program.

**Comment by peterwittek** [comment]
My bad, I was sloppy. Please take a look at commit fb3f8dae004d361dc02997c31a7ad42ecc59e8d6.

**Comment by yoch** [comment]
I think this is OK now.

**Comment by peterwittek** [comment]
Okay, I close it then. Thanks again for reporting this: it was a major conceptual mistake that went unnoticed for years.
