### ISSUE TITLE
somoclu to regenerate the same map if run multiple times on the same dataset

### ISSUE THREAD

**Issue by passionato** [peterwittek/somoclu#78]
I was wondering if there was any parameter to set in order to control the SOM. each time I run the som algo on my dataset, I get different map and results, how can I introduce a variable to set the randomness value so that if I run it multiple times on the same dataset I can get the same output?
thanks

**Comment by peterwittek** [comment]
We just resolved a related bug in #76, making Somoclu actually stochastic. The way to get around it is to generate a random initial codebook yourself and pass this same codebook every time you train a new SOM. Make sure the random values are in [0,1]. Option B: ask for PCA initialization.

**Comment by passionato** [comment]
my bad, so it was a very recent issue, and i accidently hit on that also.
`myinitcodebook = np.random.uniform(low=0.0, high=1.0, size=(5,))`
`som = somoclu.Somoclu(n_columns, n_rows, initialcodebook=myinitcodebook, maptype="planar")`

please correct me if i am wrong in initializing the codebook, however i get the following error:

Warning: data was not float32. A 32-bit copy was made

> [[11:47:51.384]] [LOG]   { [Error: Closing remaining open files:../py-project/Data.h5...done]
>   traceback: 'Traceback (most recent call last):\n  
> ...
>     som.train(self.matrix_data, epochs=self.iterations, scalecooling=\'exponential\')\n  File "/usr/local/lib/python2.7/dist-packages/somoclu-1.7.3-py2.7-linux-x86_64.egg/somoclu/train.py", line 209, in train\n    self._init_codebook()\n  File "/usr/local/lib/python2.7/dist-packages/somoclu-1.7.3-py2.7-linux-x86_64.egg/somoclu/train.py", line 513, in _init_codebook\n    raise Exception("Invalid size for initial codebook")\nException: Invalid size for initial codebook\n
> 

I have cloned and installed the new version of the somoclu from github, though.

**Comment by peterwittek** [comment]
It should be
```python
myinitcodebook = np.random.uniform(low=0.0, high=1.0, size=(n_columns * n_rows * n_dim))
```

**Comment by passionato** [comment]
thanks.
So i am still not getting the same output each time i run the somoclu.
Here is my code:

```
n_rows, n_columns = 20, 20
my_code = np.float32(np.random.uniform(low=0.0, high=1.0, size=(n_columns * n_rows * 4)))

som = somoclu.Somoclu(n_columns, n_rows, initialcodebook=my_code, maptype="planar", gridtype="rectangular", neighborhood="gaussian", std_coeff=1.0, initialization=None, verbose=2)
som.train(mydata, epochs=10, scalecooling='exponential')
som.view_umatrix(bestmatches=True, labels=labels, filename="umatrix_output" )
som_state = som.get_surface_state()
my_bmus = som.get_bmus(som_state)
```

then I use the `my_bmus` to get the X and Y s to draw my personal map. 


what am I missing here that makes that i don't get the same output for my dataset?

**Comment by peterwittek** [comment]
Stupid question: are you rerunning the second line? If so, you get a new random initial map every time.

**Comment by passionato** [comment]
it is not stupid question at all, I have forgotten to include a random seed:
`np.random.seed(5)`

However, the shape of the map is almost the same, but some other feature that i have added onto it, get totally changed, for which I use the same output from the som as well.
maybe there is some other parameter which is getting in the way.

**Comment by peterwittek** [comment]
There is one more element of stochasticity: it is unpredictable how the parallelization will distribute the chunks of the data to different cores, and the final map is sensitive to the order. You have two options to make it fully deterministic:

1. Set environment variable `OMP_NUM_THREADS=1` to disable parallelism.

2. Run the GPU kernel (you can only use one GPU from the Python wrapper).

**Comment by passionato** [comment]
thanks for your answer.

**Comment by passionato** [comment]
so basically it is not recommended to use both `initialcodebook=mycodebook` and `initialization=None` or `initialization="pca"` at the same time? either initialization or initialcodebook should be used?

**Comment by peterwittek** [comment]
Yes, that is correct. Unless you have access to a large-scale quantum computer that can put several different initial codebooks in superposition...
