### ISSUE TITLE
update citation

### ISSUE THREAD

**Issue by xgdgsc** [peterwittek/somoclu#81]
@peterwittek Do we just update Rsomoclu to 1.7.3.1 - or increase all releases to 1.7.4 ?

**Comment by peterwittek** [comment]
We had an important bug fix, so the version number bump is justified. I just did that, and updated the references. Please check if all is fine, and then I tag the release.

**Comment by peterwittek** [comment]
It all looked fine to me, so I tagged the new version and released it. Please update the usual outlets.
