### ISSUE TITLE
1.7.4 build fails on Redhat EL 7.2

### ISSUE THREAD

**Issue by Gracklewolf** [peterwittek/somoclu#82]
# make
make -C src all
make[1]: Entering directory `/cluster/app/somoclu/src/somoclu/src'

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o sparseCpuKernels.o -c sparseCpuKernels.cpp

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o denseCpuKernels.o -c denseCpuKernels.cpp

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o mapDistanceFunctions.o -c mapDistanceFunctions.cpp

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o training.o -c training.cpp

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o uMatrix.o -c uMatrix.cpp

/usr/local/cuda-8.0/bin/nvcc -DHAVE_CONFIG_H -I/usr/local/cuda-8.0/include -use_fast_math -Xcompiler "-fPIC -fopenmp -O3 -ffast-math -march=native" -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o denseGpuKernels.cu.co -c denseGpuKernels.cu

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o io.o -c io.cpp

mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -O3 -ffast-math -march=native -DCLI -I/cluster/app/openmpi/2.0.2/include -I. -I.. -o somoclu.o -c somoclu.cpp

somoclu.cpp: In function ‘int main(int, char**)’:

somoclu.cpp:331:50: error: ‘strcpy’ was not declared in this scope

         strcpy(inFilenameCStr, inFilename.c_str());
                                                  ^
somoclu.cpp:338:44: error: ‘strcpy’ was not declared in this scope

         strcpy(mapTypeCStr, mapType.c_str());
                                            ^
somoclu.cpp:345:46: error: ‘strcpy’ was not declared in this scope

         strcpy(gridTypeCStr, gridType.c_str());
                                              ^
make[1]: *** [somoclu.o] Error 1

make[1]: Leaving directory `/cluster/app/somoclu/src/somoclu/src'

make: *** [all] Error 2

**Comment by Gracklewolf** [comment]
I fixed the build by editing src/somoclu.cpp and adding these lines:
#include <stdlib.h>
#include <string.h>

Also, in src/Makefile, the MPI_LIBDIR variable appears to need "-L" in front of it if you define where to find MPI.

**Comment by peterwittek** [comment]
Thanks for reporting this. Commit dde5ce8ea208d887283ca07665dda1b0e3b8ef2a hopefully settles this.

The MPI_LIBDIR should be fine. I tried this:
```bash
./configure  --with-mpi-libdir=/whatever
```
and it displayed this:
```
...
 Somoclu Version 1.7.4

 Prefix: /usr/local.
 Compiler: mpic++ -fPIC -fopenmp -O3 -ffast-math -march=native -I/usr/include -L/whatever -lmpi
...
```
