### ISSUE TITLE
NameError: global name 'wrap_train' is not defined

### ISSUE THREAD

**Issue by bharadwaj509** [peterwittek/somoclu#83]
I installed the whole package according to the following file:
https://somoclu.readthedocs.io/en/stable/download.html

I am running a sample example from the following.
https://somoclu.readthedocs.io/en/stable/example.html

I am on ubuntu 16 and python 2.7 

I am getting the following error 

**NameError: global name 'wrap_train' is not defined**

This is the following code where I am getting the error: 
som.train(data)

Help me with this error.

**Comment by peterwittek** [comment]
I assume you tried to compile it from the source. Either try to install it with pip or see issue #28 for problems and solutions related to compilation.

**Comment by bharadwaj509** [comment]
Sure Peter.

Thanks very much.

*Thanks and Regards,*

*Baradwaj Aryasomayajula,*

*Masters - CS | University of Cincinnati, Cincinnati, Ohio, US 45220*

*(513) 371-8032*

**Comment by bharadwaj509** [comment]
I am getting the following warning while importing the somoclu:
Warning: training function cannot be imported. Only pre-trained maps can be analyzed.
In [5]:

**Comment by bharadwaj509** [comment]
These are the files I have in anaconda python somoclu

/home/arya_b/anaconda2/lib/python2.7/site-packages/_somoclu_wrap.so
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/DESCRIPTION.rst
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/INSTALLER
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/METADATA
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/RECORD
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/WHEEL
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/metadata.json
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu-1.7.4.dist-info/top_level.txt
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/__init__.py
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/__init__.pyc
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/somoclu_wrap.py
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/somoclu_wrap.pyc
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/train.py
  /home/arya_b/anaconda2/lib/python2.7/site-packages/somoclu/train.pyc

**Comment by bharadwaj509** [comment]
@xgdgsc @peterwittek Can you check the above error. I saw all the suggestions through the issue #28. It is still not working. For mac there is no libiomp anywhere. I tried the updated location too.

**Comment by bharadwaj509** [comment]
I think I don't have this. _somoclu_wrap.[YOUR ARCH].pyd under site-package folder

**Comment by xgdgsc** [comment]
You have `_somoclu_wrap.so` which should work. Maybe you can try system python instead of anaconda one.

**Comment by bharadwaj509** [comment]
@xgdgsc did that too...

**Comment by xgdgsc** [comment]
I just tried it in windows subsystem for linux (ubuntu 16.04) and a fresh install virtual machine of ubuntu 16.04, both works well without any warning.

**Comment by bharadwaj509** [comment]
@xgdgsc Sure. I will do that. Will try to run in an virtual machine and get back to you.

**Comment by xgdgsc** [comment]
Yes. I used python 2.7 in system.

**Comment by bharadwaj509** [comment]
@xgdgsc I started working on an aws instance. I am able to run it on python 2.7. 

Now my doubt is can I get the boundaries of the clusters formed. Which methods should I edit in order to do that. 

Should I open it as a new issue.

**Comment by xgdgsc** [comment]
@bharadwaj509 Not sure what do you mean by boundaries.

**Comment by peterwittek** [comment]
Clustering is done via standard clustering algorithms in scikit-learn. You can also take a look at #66 for more info.

**Comment by bharadwaj509** [comment]
Can I just change the python code if I want to make any edits?

**Comment by peterwittek** [comment]
If you change the Python code, nothing has to be compiled again. Just make sure you reload the module.

**Comment by bharadwaj509** [comment]
Ok. Thanks Peter.

**Comment by compmonks** [comment]
Is there a wheel for py35? Currently running somoclu-1.7.4 on a virtualenv on MAC and getting this wrap train error (NameError: name 'wrap_train' is not defined). the somoclu_wrap.so file is not in site-packages. I installed somoclu through pip
