### ISSUE TITLE
somoclu project

### ISSUE THREAD

**Issue by baslyhend** [peterwittek/somoclu#88]
I'm very interesting of somoclu project. Therefore, I have some questions about:
- I want to execute the code source of somoclu using VS 2013 and CUDA 7.5, is it necessary to use the other files of Matlab, R and Python to compile it?
- If not, I have some errors to compile the project as  "debug error R6010 - abort() has been called". Can you help me please to resolve this kind of errors?

**Comment by peterwittek** [comment]
@xgdgsc, any insight on this? The README says we support VS 2013+CUDA 7.5.

**Comment by xgdgsc** [comment]
We updated the version to 2015 and CUDA 8 in https://github.com/peterwittek/somoclu/commit/5bf63ff75d30f9b9da35a638be7d4bfc4e20ddea , maybe we forgot to update the readme.

 You don' t need the other files if you want to just use the cpp cli version. 

https://stackoverflow.com/questions/28210235/what-is-a-r6010-error . Is it a release build or debug build?

**Comment by peterwittek** [comment]
Thanks. Could you update the README?

**Comment by xgdgsc** [comment]
OK. I will do.

**Comment by baslyhend** [comment]
thank you. i will try with VS 2015 and cuda 8.0.
