### ISSUE TITLE
makemex-GPU-sh not compiling/building

### ISSUE THREAD

**Issue by shomedas** [peterwittek/somoclu#9]
somoclu command line is working fine.(i tried the example:somoclu data/rgbs.txt data/rgbs. it worked fine.)

then i tried ./configure --without-mpi --with-cuda=/usr/local/cuda-6.5. then make, make install. it built fine. but when i try

      MEX_BIN="/usr/local/MATLAB/R2014a/bin/mex" ./makeMex-GPU.sh

I get error "Unknown file extension '.co'."
other details:
ubuntu 14.04, matlab2014a, gcc4.8.2, cuda-6.5, Nvidia-gt740

**Comment by xgdgsc** [comment]
try modify the script with `mex -v` to paste more information here.

**Comment by shomedas** [comment]
makeMex-GPU.sh script:

#!/bin/sh
if [ -z "$MEX_BIN" ]
    then MEX_BIN="/usr/local/MATLAB/R2013a/bin/mex"
fi
CUDA_LIB="/usr/local/cuda-6.5/lib64"
$MEX_BIN -I../ MexSomoclu.cpp -DCUDA ../denseCpuKernels.o ../io.o ../sparseCpuKernels.o ../training.o ../mapDistanceFunctions.o ../uMatrix.o ..
/denseGpuKernels.cu.co -lgomp -L$CUDA_LIB -lcudart -lcublas -lnvblas

trying to build mex-gpu:
MEX_BIN="/usr/local/MATLAB/R2014a/bin/mex" ./makeMex-GPU.sh
Verbose mode is on.
Unknown file extension '.co'.

do i have to run ./makemex-sh first?

**Comment by xgdgsc** [comment]
No, you don' t. I only tested the script with 2013a. I will test with 2014a later.

**Comment by peterwittek** [comment]
Did you have a chance to look into this? I also only have 2013a.

**Comment by xgdgsc** [comment]
As the referenced commit above, changing .co to .o works for 2014

**Comment by peterwittek** [comment]
I see, thanks. When you merge that branch, we can close this issue.

**Comment by peterwittek** [comment]
I checked the shell script. It should be fine, I am closing this.
