### ISSUE TITLE
[enhancement] the sparse kernel complexity can be greatly improved

### ISSUE THREAD

**Issue by yoch** [peterwittek/somoclu#91]
Hi,

We recently published a conference paper on this subject (http://www.ai.univ-paris8.fr/~jmelka/IJCCI_2017_20.pdf).

Our open-source implementation is available here: https://github.com/yoch/sparse-som

**Comment by peterwittek** [comment]
This is pretty awesome. Any chance to add the changes to Somoclu?

**Comment by yoch** [comment]
Yep, I think it's very possible, but I need to have some free time (and to be a bit more familiar with MPI).

**Comment by peterwittek** [comment]
Thanks, that would be great! The MPI part is fairly trivial: only the data is split across processes, and thus the codebook has to be synced after a batch is processed in every process.

**Comment by yoch** [comment]
I made a first attempt [here](https://github.com/yoch/somoclu/tree/sparse-som), so you can try it and play with. The added code follows the principle of minimal change (I didn't change the sparse format to be more conventional, for example).

Please note that the sparse dot product introduces some memory latency (it's hard to reach the full CPU power with scattered accesses to memory), but it's still much faster than the naive approach, especially in case of very sparse data.

**Comment by peterwittek** [comment]
Wow, this is really clever. MPI chokes on the sparse kernel at the moment, both on the old one and the new one. I would like to merge your changes and then debug the MPI problems. Could you send a PR?

**Comment by yoch** [comment]
done (#94)

**Comment by peterwittek** [comment]
Thanks very much.

**Comment by yoch** [comment]
It can be interesting to test the new kernel with the same data as [here](http://peterwittek.com/training-emergent-self-organizing-maps-with-somoclu.html).

**Comment by peterwittek** [comment]
The [journal version](https://www.jstatsoft.org/article/view/v078i09) of the paper has the scripts for reproducing benchmarks. It does not have the exact same vector space, but it includes a script for generating sparse data, so the overall characteristics are easy to replicate.
