### ISSUE TITLE
Python: override distance function?

### ISSUE THREAD

**Issue by r0f1** [peterwittek/somoclu#92]
Hi,
I would like to use my custom distance function. In the methods `view_activation_map()` and `get_surface_state()` you make a call to `scipy.spatial.distance.cdist()` and use the euclidean distance. Is there a way to use my own distance function either via subclassing Somoclu or providing a distance matrix to Somoclu?

**Comment by peterwittek** [comment]
By all means, go for it. I am happy to merge a pull request. The only thing is that during training, only the Euclidean distance is considered (either toroid or planar, hexagonal or rectangular grid). If you are happy that the analysis of the map uses a different distance function, then the easiest way to do this is to have an optional parameter for the two functions you mention as the distance function to be used.
