### ISSUE TITLE
MPI 2 support broken in sparse kernel

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/somoclu#95]
It segfaults when the number of processes is greater than 1.

**Comment by yoch** [comment]
Can you give a test case please ? I made a few tests without error.

**Comment by peterwittek** [comment]
I compiled Somoclu with OpenMPI 2.1.1, with GCC 7.2.0. Then, when I try 
```bash
mpirun -np 2 src/somoclu -k 2 data/rgbs.svm data/sparse
```
it segfaults. Setting `-np 1` is fine, so the compilation in general is okay.

**Comment by yoch** [comment]
I tried with MPI 1.10 and GCC 5.4 and it works. I guess this is related to MPI 2 version.

**Comment by peterwittek** [comment]
Yes, I think you are right. I change the title.
